<script setup lang="ts">
import Swal from 'sweetalert2'

const api = useKoperasiApi()
const currentUser = ref<any>(null)
const authReady = ref(false)
const loginError = ref('')
const loginForm = reactive({ email:'', password:'' })
const { formatNumber, setCurrency } = useCurrencyInput()
const { downloadExcel, downloadWorkbook, parseExcel } = useExcelData()
const allNav = [
  ['dashboard', 'Dashboard'], ['items', 'Barang'], ['customers', 'Pelanggan'], ['suppliers', 'Supplier'],
  ['sale', 'Kasir'], ['purchase', 'Pembelian'], ['history', 'Histori'], ['debts', 'Piutang'], ['masters', 'Pengaturan Barang'], ['users', 'Pengguna'],
]
const nav = computed(()=>allNav.filter(([key])=>key!=='users'?currentUser.value?.role!=='viewer'||['dashboard','items'].includes(key):currentUser.value?.role==='admin'))
const active = ref('dashboard')
const dashboardYear = ref(new Date().getFullYear())
const dashboardMonth = ref(new Date().getMonth()+1)
const years = Array.from({length:5},(_,i)=>new Date().getFullYear()-i)
const loading = ref(false)
const submitting = ref(false)
const error = ref('')
const notice = ref('')
const data = reactive<any>({ dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[],users:[] })
const userForm = reactive<any>({ name:'',email:'',password:'',role:'cashier',active:true })
const userModal = ref(false)
const editingUser = ref<number|null>(null)
const itemForm = reactive<any>({ sku:'',name:'',description:'',supplier_id:null,category_id:null,brand_id:null,brand_name:'',unit_id:null,stock:0,cost:0,price:0 })
const customerForm = reactive<any>({ code:'',name:'',phone:'',address:'' })
const supplierForm = reactive<any>({ code:'',name:'',phone:'',address:'' })
const transactionForm = reactive<any>({ customer_id:null,supplier_id:null,payment_method_id:null,paid_amount:0,notes:'',items:[{item_id:null,quantity:1,unit_price:0}] })
const transactionContext = ref<'sale'|'purchase'>('sale')
const masterForm = reactive({ table:'categories', name:'' })
const editing = reactive<any>({ item:null, customer:null, supplier:null, master:null, transaction:null })
const expandedTransaction = ref<number|null>(null)
const selectedReceipt = ref<any>(null)
const printMode = ref<null|'monthly'|'receipt'>(null)
const debtPayments = reactive<Record<number, number>>({})
const itemImport = ref<HTMLInputElement|null>(null)
const customerImport = ref<HTMLInputElement|null>(null)
const supplierImport = ref<HTMLInputElement|null>(null)
const modal = ref<null|'item'|'customer'|'supplier'>(null)
const filters = reactive({ itemSearch:'', category:'', stock:'', customerSearch:'', supplierSearch:'', historySearch:'', historyType:'', historyStatus:'' })
const months = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
const maxSales = computed(()=>Math.max(...(data.dashboard.monthly_sales||[0]),1))

const money = (v:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const itemById = (id:number) => data.items.find((v:any)=>v.id===Number(id))
const lineTotal = computed(()=>transactionForm.items.reduce((sum:number,line:any)=>sum+(Number(line.quantity)||0)*(Number(line.unit_price)||0),0))
const changeAmount = computed(()=>Number(transactionForm.paid_amount||0)-lineTotal.value)
const transactionItems = computed(()=>active.value==='purchase'?data.items.filter((v:any)=>Number(v.supplier_id)===Number(transactionForm.supplier_id)):data.items)
const filteredItems = computed(()=>data.items.filter((v:any)=>{
  const query=filters.itemSearch.toLowerCase();const matchesQuery=!query||[v.sku,v.name,v.category_name,v.brand_name].some(x=>String(x||'').toLowerCase().includes(query));
  const matchesCategory=!filters.category||String(v.category_id)===filters.category;
  const matchesStock=!filters.stock||(filters.stock==='empty'?Number(v.stock)===0:filters.stock==='low'?Number(v.stock)>0&&Number(v.stock)<=5:Number(v.stock)>5);
  return matchesQuery&&matchesCategory&&matchesStock
}))
const filteredCustomers = computed(()=>data.customers.filter((v:any)=>!filters.customerSearch||[v.code,v.name,v.phone].some(x=>String(x||'').toLowerCase().includes(filters.customerSearch.toLowerCase()))))
const filteredSuppliers = computed(()=>data.suppliers.filter((v:any)=>!filters.supplierSearch||[v.code,v.name,v.phone,v.address].some(x=>String(x||'').toLowerCase().includes(filters.supplierSearch.toLowerCase()))))
const filteredTransactions = computed(()=>data.transactions.filter((v:any)=>{const query=filters.historySearch.toLowerCase();const matchesSearch=!query||[v.invoice_no,v.customer_name,v.supplier_name,v.notes].some(x=>String(x||'').toLowerCase().includes(query));const matchesType=!filters.historyType||v.transaction_type===filters.historyType;const matchesStatus=!filters.historyStatus||(filters.historyStatus==='ACTIVE'?v.status==='ACTIVE':filters.historyStatus==='VOID'?v.status==='VOID':v.payment_status===filters.historyStatus);return matchesSearch&&matchesType&&matchesStatus}))
const jakartaYearMonth=(value:string)=>{const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'numeric',timeZone:'Asia/Jakarta'}).formatToParts(new Date(value));return {year:Number(parts.find(v=>v.type==='year')?.value),month:Number(parts.find(v=>v.type==='month')?.value)}}
const monthlyReportTransactions = computed(()=>data.transactions.filter((v:any)=>{const date=jakartaYearMonth(v.transaction_date);return v.transaction_type==='SALE'&&v.status==='ACTIVE'&&date.year===dashboardYear.value&&date.month===dashboardMonth.value}))
const monthlyReportTotal = computed(()=>monthlyReportTransactions.value.reduce((sum:number,v:any)=>sum+Number(v.grand_total||0),0))
const dashboardPeriods = computed(()=>[
  {label:'Hari Ini',value:data.dashboard.today||{}},
  {label:'Kemarin',value:data.dashboard.yesterday||{}},
  {label:`${months[dashboardMonth.value-1]} ${dashboardYear.value}`,value:data.dashboard.selected_month||{}},
  {label:`Tahun ${dashboardYear.value}`,value:data.dashboard.selected_year||{}},
])
const dailyTotals = computed(()=>(data.dashboard.daily||[]).reduce((sum:any,row:any)=>({income:sum.income+Number(row.income||0),expense:sum.expense+Number(row.expense||0),debt:sum.debt+Number(row.debt||0),net_income:sum.net_income+Number(row.net_income||0)}),{income:0,expense:0,debt:0,net_income:0}))
const jakartaDateTime = (value:string) => new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value))

async function load() {
  loading.value=true; error.value=''
  try {
    const [dashboard,items,customers,suppliers,categories,brands,units,payment_methods,transactions,debts] = await Promise.all([
      api.dashboard(dashboardYear.value,dashboardMonth.value),api.items(),api.customers(),api.suppliers(),api.masters('categories'),api.masters('brands'),api.masters('units'),api.masters('payment_methods'),api.transactions(),api.debts(),
    ])
    Object.assign(data,{dashboard,items,customers,suppliers,categories,brands,units,payment_methods,transactions,debts})
    if(currentUser.value?.role==='admin')data.users=await api.users()
    if (!transactionForm.customer_id) transactionForm.customer_id=customers.find((c:any)=>c.code==='UMUM')?.id
  } catch(e:any){error.value=e?.data?.message||e.message||'Gagal memuat data'} finally{loading.value=false}
}
async function submit(action:()=>Promise<any>, message:string, confirmation:string|false=false){if(submitting.value)return false;if(confirmation!==false){const result=await Swal.fire({icon:'question',title:'Konfirmasi',text:confirmation,showCancelButton:true,confirmButtonText:'Ya, simpan',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!result.isConfirmed)return false}error.value='';notice.value='';submitting.value=true;try{await action();await load();await Swal.fire({icon:'success',title:'Berhasil',text:message,confirmButtonColor:'#1d6b43'});return true}catch(e:any){const message=e?.data?.message||e.message||'Gagal menyimpan data';await Swal.fire({icon:'error',title:'Gagal',text:message,confirmButtonColor:'#1d6b43'});return false}finally{submitting.value=false}}
watch(active,(next)=>{error.value='';notice.value='';modal.value=null;if((next==='sale'||next==='purchase')&&transactionContext.value!==next){resetTransaction(next);transactionContext.value=next}})
watch(()=>transactionForm.supplier_id,()=>{if(active.value==='purchase'){transactionForm.items=transactionForm.items.map((line:any)=>transactionItems.value.some((v:any)=>v.id===Number(line.item_id))?line:{item_id:null,quantity:1,unit_price:0})}})
watch(dashboardYear,load)
watch(dashboardMonth,load)
watch(()=>customerForm.phone,v=>{const clean=String(v||'').replace(/\D/g,'');if(v!==clean)customerForm.phone=clean})
watch(()=>supplierForm.phone,v=>{const clean=String(v||'').replace(/\D/g,'');if(v!==clean)supplierForm.phone=clean})
function nullableNumber(v:any){return v?Number(v):null}
async function saveItem(){const saved=await submit(async()=>{const brandID=await findOrCreateMaster('brands',data.brands,itemForm.brand_name);const payload={...itemForm,supplier_id:nullableNumber(itemForm.supplier_id),category_id:nullableNumber(itemForm.category_id),brand_id:brandID,unit_id:nullableNumber(itemForm.unit_id),stock:Number(itemForm.stock),cost:Number(itemForm.cost),price:Number(itemForm.price)};return editing.item?api.updateItem(editing.item,payload):api.createItem(payload)},editing.item?'Barang berhasil diubah':'Barang berhasil ditambahkan');if(saved)cancelItem()}
function openItem(v:any=null){cancelItem(false);if(v){editing.item=v.id;Object.assign(itemForm,v)}modal.value='item'}
function editItem(v:any){openItem(v)}
function cancelItem(close=true){editing.item=null;Object.assign(itemForm,{sku:'',name:'',description:'',supplier_id:null,category_id:null,brand_id:null,brand_name:'',unit_id:null,stock:0,cost:0,price:0});if(close)modal.value=null}
async function removeItem(v:any){const result=await Swal.fire({icon:'warning',title:`Hapus ${v.name}?`,text:'Data yang sudah dihapus tidak dapat dikembalikan.',showCancelButton:true,confirmButtonText:'Hapus',cancelButtonText:'Batal',confirmButtonColor:'#b8322a'});if(result.isConfirmed)await submit(()=>api.deleteItem(v.id),'Barang berhasil dihapus')}
async function saveParty(kind:'customer'|'supplier'){const form=kind==='customer'?customerForm:supplierForm;const id=editing[kind];if(await submit(()=>kind==='customer'?(id?api.updateCustomer(id,form):api.createCustomer(form)):(id?api.updateSupplier(id,form):api.createSupplier(form)),`${kind==='customer'?'Pelanggan':'Supplier'} berhasil ${id?'diubah':'ditambahkan'}`))closeParty(kind)}
function openParty(kind:'customer'|'supplier',v:any=null){if(v?.code==='UMUM')return;editing[kind]=v?.id||null;const form=kind==='customer'?customerForm:supplierForm;Object.keys(form).forEach(k=>form[k]='');if(v)Object.assign(form,v);modal.value=kind}
function editParty(kind:'customer'|'supplier',v:any){openParty(kind,v)}
function closeParty(kind:'customer'|'supplier'){editing[kind]=null;const form=kind==='customer'?customerForm:supplierForm;Object.keys(form).forEach(k=>form[k]='');modal.value=null}
async function removeParty(kind:'customer'|'supplier',v:any){if(v.code==='UMUM')return;const result=await Swal.fire({icon:'warning',title:`Hapus ${v.name}?`,showCancelButton:true,confirmButtonText:'Hapus',cancelButtonText:'Batal',confirmButtonColor:'#b8322a'});if(result.isConfirmed)await submit(()=>kind==='customer'?api.deleteCustomer(v.id):api.deleteSupplier(v.id),`${kind==='customer'?'Pelanggan':'Supplier'} berhasil dihapus`)}
function openMaster(table:string){masterForm.table=table;active.value='masters'}
function blockInvalidNumber(event:KeyboardEvent){const target=event.target as HTMLInputElement;if(target?.type==='number'&&['e','E','+','-','.'].includes(event.key))event.preventDefault()}
function sanitizeNumeric(event:Event){const target=event.target as HTMLInputElement;if(target?.type==='tel')target.value=target.value.replace(/\D/g,'')}
async function voidTransaction(v:any){const stockEffect=v.transaction_type==='SALE'?'Stok barang penjualan akan dikembalikan.':'Stok dari pembelian akan dikurangi; pembatalan ditolak jika stok sudah terpakai.';const result=await Swal.fire({icon:'warning',title:`Batalkan ${v.invoice_no}?`,text:stockEffect,input:'textarea',inputLabel:'Alasan pembatalan',inputPlaceholder:'Tulis alasan (minimal 5 karakter)',showCancelButton:true,confirmButtonText:'Ya, batalkan',cancelButtonText:'Kembali',confirmButtonColor:'#b8322a',inputValidator:(value)=>!value||value.trim().length<5?'Alasan pembatalan minimal 5 karakter.':undefined});if(!result.isConfirmed)return;await submit(()=>api.voidTransaction(v.id,result.value.trim()),`Transaksi dibatalkan. ${stockEffect}`,false)}
async function saveMaster(){const id=editing.master;if(await submit(()=>id?api.updateMaster(masterForm.table,id,masterForm):api.createMaster(masterForm.table,masterForm),`Data berhasil ${id?'diubah':'ditambahkan'}`)){editing.master=null;masterForm.name=''}}
function editMaster(table:string,v:any){masterForm.table=table;masterForm.name=v.name;editing.master=v.id}
async function deleteMaster(table:string,v:any){if(confirm(`Hapus ${v.name}?`))await submit(()=>api.deleteMaster(table,v.id),'Data berhasil dihapus',false)}
function chooseItem(line:any){const item=itemById(line.item_id);if(item)line.unit_price=active.value==='purchase'?item.cost:item.price}
function addLine(){transactionForm.items.push({item_id:null,quantity:1,unit_price:0})}
function resetTransaction(context: string=active.value){editing.transaction=null;transactionContext.value=context==='purchase'?'purchase':'sale';Object.assign(transactionForm,{customer_id:context==='sale'?data.customers.find((c:any)=>c.code==='UMUM')?.id||null:null,supplier_id:null,payment_method_id:null,paid_amount:0,notes:'',items:[{item_id:null,quantity:1,unit_price:0}]})}
function editTransaction(v:any){if(v.status!=='ACTIVE')return;const context=v.transaction_type==='SALE'?'sale':'purchase';transactionContext.value=context;editing.transaction=v.id;Object.assign(transactionForm,{customer_id:v.customer_id,supplier_id:v.supplier_id,payment_method_id:v.payment_method_id,paid_amount:v.amount_received,notes:v.notes||'',items:v.items.map((line:any)=>({item_id:line.item_id,quantity:line.quantity,unit_price:line.unit_price}))});active.value=context}
async function saveTransaction(type:'SALE'|'PURCHASE') {const payload={...transactionForm,transaction_type:type,customer_id:type==='SALE'?Number(transactionForm.customer_id):null,supplier_id:type==='PURCHASE'?Number(transactionForm.supplier_id):null,payment_method_id:transactionForm.payment_method_id?Number(transactionForm.payment_method_id):null,paid_amount:Number(transactionForm.paid_amount),items:transactionForm.items.map((v:any)=>({...v,item_id:Number(v.item_id),quantity:Number(v.quantity),unit_price:Number(v.unit_price)}))};const id=editing.transaction;if(await submit(()=>id?api.updateTransaction(id,payload):api.createTransaction(payload),`${type==='SALE'?'Penjualan':'Pembelian'} berhasil ${id?'diubah':'dicatat'}`,`${id?'Simpan perubahan':'Simpan'} ${type==='SALE'?'penjualan':'pembelian'} sebesar ${money(lineTotal.value)}?`))resetTransaction() }
async function payDebt(v:any){const amount=Number(debtPayments[v.id]||0);if(await submit(()=>api.payDebt(v.id,{amount}),'Pembayaran piutang berhasil dicatat'))debtPayments[v.id]=0}
async function exportData(kind:'items'|'customers'|'suppliers'|'transactions'){
  const date=new Date().toISOString().slice(0,10)
  if(kind==='items')await downloadExcel(`barang-${date}.xlsx`,['sku','name','description','supplier_code','category','brand','unit','stock','cost','price'],data.items.map((v:any)=>[v.sku,v.name,v.description,data.suppliers.find((s:any)=>s.id===v.supplier_id)?.code||'',v.category_name||'',v.brand_name||'',v.unit_name||'',v.stock,v.cost,v.price]))
  if(kind==='customers')await downloadExcel(`pelanggan-${date}.xlsx`,['code','name','phone','address'],data.customers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='suppliers')await downloadExcel(`supplier-${date}.xlsx`,['code','name','phone','address'],data.suppliers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='transactions')await downloadExcel(`histori-transaksi-${date}.xlsx`,['invoice','date','type','party','status','payment_status','total','received','change','items','notes'],filteredTransactions.value.map((v:any)=>[v.invoice_no,v.transaction_date,v.transaction_type,v.customer_name||v.supplier_name||'',v.status,v.payment_status,v.grand_total,v.amount_received,v.change_amount,v.items.map((x:any)=>`${x.item_name} (${x.quantity} x ${x.unit_price})`).join('; '),v.notes]))
}
async function login(){loginError.value='';submitting.value=true;try{const result=await api.login(loginForm.email,loginForm.password);api.token.value=result.access_token;currentUser.value=result.user;loginForm.password='';await load()}catch(e:any){loginError.value=e?.data?.message||'Login gagal'}finally{submitting.value=false}}
function logout(){api.token.value=null;currentUser.value=null;active.value='dashboard';Object.assign(data,{dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[]})}
function openUser(user:any=null){editingUser.value=user?.id||null;Object.assign(userForm,user?{name:user.name,email:user.email,password:'',role:user.role,active:user.active}:{name:'',email:'',password:'',role:'cashier',active:true});userModal.value=true}
function closeUser(){editingUser.value=null;userModal.value=false;Object.assign(userForm,{name:'',email:'',password:'',role:'cashier',active:true})}
async function saveUser(){const id=editingUser.value;const body={...userForm};if(!body.password)delete body.password;if(await submit(()=>id?api.updateUser(id,body):api.createUser(body),`Pengguna berhasil ${id?'diubah':'ditambahkan'}`))closeUser()}
async function removeUser(user:any){if(String(user.id)===String(currentUser.value.id)){await Swal.fire({icon:'warning',title:'Tidak dapat menghapus akun sendiri',confirmButtonColor:'#1d6b43'});return}const result=await Swal.fire({icon:'warning',title:`Hapus ${user.name}?`,text:'Pengguna tidak dapat login lagi.',showCancelButton:true,confirmButtonText:'Hapus',cancelButtonText:'Batal',confirmButtonColor:'#b8322a'});if(result.isConfirmed)await submit(()=>api.deleteUser(user.id),'Pengguna berhasil dihapus',false)}
function findByName(values:any[],name:string){return values.find((v:any)=>String(v.name).toLowerCase()===String(name).toLowerCase())?.id||null}
async function findOrCreateMaster(table:'categories'|'brands'|'units',values:any[],name:string){
  if(!String(name||'').trim())return null
  const existing=findByName(values,name);if(existing)return existing
  await api.createMaster(table,{name:String(name).trim()})
  const refreshed=await api.masters(table);values.splice(0,values.length,...refreshed)
  return findByName(values,name)
}
function sameText(a:any,b:any){return String(a??'').trim()===String(b??'').trim()}
function sameCode(a:any,b:any){return String(a??'').trim().toLowerCase()===String(b??'').trim().toLowerCase()}
async function importData(kind:'items'|'customers'|'suppliers',event:Event){
  const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return
  try{
    const rows=await parseExcel(file);if(!rows.length)throw new Error('Excel kosong atau formatnya tidak sesuai template export.')
    const confirm=await Swal.fire({icon:'question',title:`Import ${rows.length} baris?`,text:'Data dengan kode yang sama akan diperbarui.',showCancelButton:true,confirmButtonText:'Ya, import',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!confirm.isConfirmed)return
    submitting.value=true
    let created=0,updated=0,skipped=0
    const knownCustomers=[...data.customers],knownSuppliers=[...data.suppliers],knownItems=[...data.items]
    for(let index=0;index<rows.length;index++){
      const row:any=rows[index]
      try{
        if(kind==='customers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi');if(String(row.code).toUpperCase()==='UMUM'){skipped++;continue}
          const existing=knownCustomers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateCustomer(existing.id,body):api.createCustomer(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownCustomers.push({...body,id:null})
        }else if(kind==='suppliers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi')
          const existing=knownSuppliers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateSupplier(existing.id,body):api.createSupplier(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownSuppliers.push({...body,id:null})
        }else{
          if(!row.sku||!row.name)throw new Error('sku dan name wajib diisi')
          const supplier=row.supplier_code?data.suppliers.find((v:any)=>v.code.toLowerCase()===row.supplier_code.toLowerCase()):null;if(row.supplier_code&&!supplier)throw new Error(`supplier ${row.supplier_code} tidak ditemukan`)
          const body={sku:row.sku,name:row.name,description:row.description||'',supplier_id:supplier?.id||null,category_id:await findOrCreateMaster('categories',data.categories,row.category),brand_id:await findOrCreateMaster('brands',data.brands,row.brand),unit_id:await findOrCreateMaster('units',data.units,row.unit),stock:Number(row.stock||0),cost:Number(row.cost||0),price:Number(row.price||0)}
          const identical=knownItems.find((v:any)=>sameText(v.name,body.name)&&Number(v.supplier_id||0)===Number(body.supplier_id||0)&&Number(v.unit_id||0)===Number(body.unit_id||0)&&Number(v.price||0)===Number(body.price||0))
          if(identical){skipped++;continue}
          const existing=knownItems.find((v:any)=>sameCode(v.sku,row.sku));if(existing&&!existing.id)throw new Error(`sku ${row.sku} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateItem(existing.id,body):api.createItem(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownItems.push({...body,id:null})
        }
      }catch(e:any){throw new Error(`Baris ${index+2}: ${e?.data?.message||e.message}`)}
    }
    await load();await Swal.fire({icon:'success',title:'Import selesai',text:`${created} dibuat, ${updated} diperbarui, ${skipped} dilewati.`,confirmButtonColor:'#1d6b43'})
  }catch(e:any){await Swal.fire({icon:'error',title:'Import gagal',text:e.message||'File tidak dapat diproses.',confirmButtonColor:'#1d6b43'})}finally{submitting.value=false;input.value=''}
}
async function printDocument(mode:'monthly'|'receipt'){printMode.value=mode;await nextTick();window.print();printMode.value=null}
function printMonthlyReport(){printDocument('monthly')}
async function exportMonthlyReport(){
  const prompt=await Swal.fire({title:'Export laporan bulanan',input:'textarea',inputLabel:'Catatan (opsional)',inputPlaceholder:'Tambahkan catatan untuk sheet laporan…',showCancelButton:true,confirmButtonText:'Export Excel',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!prompt.isConfirmed)return
  const transactionRows=(values:any[])=>values.map(v=>[v.invoice_no,jakartaDateTime(v.transaction_date),v.customer_name||v.supplier_name||'',v.payment_method_name||'',v.payment_status,v.status,v.grand_total,v.paid_amount,v.notes||'',v.items.map((x:any)=>`${x.item_name} (${x.quantity} x ${x.unit_price})`).join('; ')])
  const sheets:any[]=[
    {name:'Ringkasan Bulanan',columns:['Metrik','Nilai'],rows:[['Periode',`${months[dashboardMonth.value-1]} ${dashboardYear.value}`],['Total pemasukan',dailyTotals.value.income],['Total pengeluaran',dailyTotals.value.expense],['Piutang dibuat',dailyTotals.value.debt],['Pendapatan bersih',dailyTotals.value.net_income],['Jumlah transaksi penjualan',monthlyReportTransactions.value.length]]},
    {name:'Penjualan Harian',columns:['Tanggal','Pemasukan','Pengeluaran','Piutang','Pendapatan Bersih'],rows:(data.dashboard.daily||[]).map((v:any)=>[v.date,v.income,v.expense,v.debt,v.net_income]).concat([['TOTAL',dailyTotals.value.income,dailyTotals.value.expense,dailyTotals.value.debt,dailyTotals.value.net_income]])},
    {name:'Riwayat Penjualan',columns:['Invoice','Tanggal WIB','Pelanggan','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='SALE'))},
    {name:'Riwayat Pembelian',columns:['Invoice','Tanggal WIB','Supplier','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='PURCHASE'))},
    {name:'Piutang',columns:['Invoice','Pelanggan','Nilai Awal','Sisa','Status','Tanggal WIB'],rows:data.debts.map((v:any)=>[v.invoice_no,v.customer_name,v.original_amount,v.remaining_amount,v.status,jakartaDateTime(v.created_at)])},
  ];if(String(prompt.value||'').trim())sheets.push({name:'Catatan',columns:['Catatan','Dibuat pada'],rows:[[String(prompt.value).trim(),jakartaDateTime(new Date().toISOString())]]})
  await downloadWorkbook(`laporan-${dashboardYear.value}-${String(dashboardMonth.value).padStart(2,'0')}.xlsx`,sheets)
}
function printReceipt(transaction:any){selectedReceipt.value=transaction;printDocument('receipt')}
onMounted(async()=>{try{if(api.token.value){currentUser.value=await api.me();await load()}}catch{api.token.value=null}finally{authReady.value=true}})
</script>

<template>
  <section v-if="authReady&&!currentUser" class="login-page"><form class="login-card" @submit.prevent="login"><div class="login-mark">K</div><h1>Masuk ke Koperasi</h1><p>Gunakan akun yang diberikan administrator.</p><label>Email<input v-model.trim="loginForm.email" type="email" autocomplete="username" required></label><label>Password<input v-model="loginForm.password" type="password" autocomplete="current-password" required></label><p v-if="loginError" class="alert error">{{loginError}}</p><button class="primary" :disabled="submitting">{{submitting?'Memproses…':'Masuk'}}</button></form></section>
  <div v-else-if="currentUser" class="app-shell">
    <aside><div class="brand"><span>K</span><div><strong>Koperasi</strong><small>Operational Console</small></div></div><nav><button v-for="n in nav" :key="n[0]" :class="{active:active===n[0]}" @click="active=n[0]">{{ n[1] }}</button></nav></aside>
    <main @keydown="blockInvalidNumber" @input="sanitizeNumeric">
      <header><div><p class="eyebrow">SIG KOPERASI · GO + NUXT</p><h1>{{ nav.find(n=>n[0]===active)?.[1] }}</h1></div><div class="user-actions"><span><b>{{currentUser.name}}</b><small>{{currentUser.role}}</small></span><button class="soft" @click="load">{{ loading?'Memuat…':'Refresh' }}</button><button class="soft" @click="logout">Keluar</button></div></header>
      <p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p>

      <section v-if="active==='users'" class="panel"><div class="page-heading"><div><h2>Pengguna</h2><p>Kelola akun dan hak akses aplikasi.</p></div><button class="primary" @click="openUser()">+ Tambah Pengguna</button></div><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr v-for="user in data.users" :key="user.id"><td><b>{{user.name}}</b><small v-if="String(user.id)===String(currentUser.id)"> · akun Anda</small></td><td>{{user.email}}</td><td><span class="role-badge">{{user.role}}</span></td><td>{{user.active?'Aktif':'Nonaktif'}}</td><td class="table-actions"><button class="soft" @click="openUser(user)">Ubah</button><button class="danger" :disabled="String(user.id)===String(currentUser.id)" @click="removeUser(user)">Hapus</button></td></tr></tbody></table></div></section>
      <template v-else-if="active==='dashboard'">
        <section class="panel dashboard-toolbar"><div><strong>Periode Laporan</strong><small>Ringkasan bulan dan tahun mengikuti pilihan ini.</small></div><select v-model.number="dashboardMonth"><option v-for="(month,i) in months" :value="i+1">{{month}}</option></select><select v-model.number="dashboardYear"><option v-for="year in years" :value="year">{{year}}</option></select><button class="primary" @click="exportMonthlyReport">Export Laporan Excel</button></section>
        <section class="period-stats"><article v-for="period in dashboardPeriods"><div><small>{{period.label}}</small><b>Pemasukan</b><strong class="income">{{money(period.value.income)}}</strong></div><div><b>Pengeluaran</b><strong class="expense">{{money(period.value.expense)}}</strong></div><div><b>Piutang Dibuat</b><strong>{{money(period.value.debt)}}</strong></div></article></section>
        <section class="operational-stats"><span>Piutang terbuka <b>{{money(data.dashboard.open_debt)}}</b></span><span>Stok menipis <b>{{data.dashboard.low_stock_items||0}} barang</b></span><span>Total barang <b>{{data.dashboard.total_items||0}}</b></span><span>Pelanggan <b>{{data.dashboard.total_customers||0}}</b></span></section>
        <section class="panel chart-panel"><div class="section-title"><div><h2>Grafik Penjualan {{dashboardYear}}</h2><small>Total nilai transaksi penjualan per bulan</small></div></div><div class="chart"><div v-for="(value,i) in data.dashboard.monthly_sales||[]" :key="Number(i)" class="bar-column"><strong>{{value?money(value):'Rp0'}}</strong><div class="bar-track"><span :style="{height:`${Math.max((value/maxSales)*100,value?4:0)}%`}"></span></div><small>{{months[Number(i)]}}</small></div></div></section>
        <section class="panel daily-report"><div class="section-title"><div><h2>Rekap Harian {{months[dashboardMonth-1]}} {{dashboardYear}}</h2><small>Perhitungan tanggal menggunakan zona waktu Asia/Jakarta (UTC+7).</small></div></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Total Pemasukan</th><th>Total Pengeluaran</th><th>Total Piutang</th><th>Total Pendapatan</th></tr></thead><tbody><tr v-for="row in data.dashboard.daily||[]" :key="row.date"><td>{{new Date(`${row.date}T00:00:00+07:00`).toLocaleDateString(`id-ID`,{weekday:`long`,day:`2-digit`,month:`short`,timeZone:`Asia/Jakarta`})}}</td><td>{{money(row.income)}}</td><td>{{money(row.expense)}}</td><td>{{money(row.debt)}}</td><td :class="row.net_income<0?`expense`:`income`">{{money(row.net_income)}}</td></tr></tbody><tfoot><tr><th>TOTAL</th><th>{{money(dailyTotals.income)}}</th><th>{{money(dailyTotals.expense)}}</th><th>{{money(dailyTotals.debt)}}</th><th>{{money(dailyTotals.net_income)}}</th></tr></tfoot></table></div></section>
        <section class="print-report" :class="{'print-target':printMode==='monthly'}"><h1>Laporan Penjualan Bulanan</h1><p>Periode: {{months[dashboardMonth-1]}} {{dashboardYear}}</p><table><thead><tr><th>Tanggal</th><th>Invoice</th><th>Pelanggan</th><th>Total</th></tr></thead><tbody><tr v-for="v in monthlyReportTransactions"><td>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</td><td>{{v.invoice_no}}</td><td>{{v.customer_name||'Umum'}}</td><td>{{money(v.grand_total)}}</td></tr><tr v-if="!monthlyReportTransactions.length"><td colspan="4">Tidak ada transaksi penjualan.</td></tr></tbody><tfoot><tr><th colspan="3">Total Penjualan</th><th>{{money(monthlyReportTotal)}}</th></tr></tfoot></table></section>
      </template>

      <template v-else-if="active==='items'">
        <div class="page-heading"><div><h2>Barang</h2><p>Kelola katalog dan persediaan barang.</p></div><div class="heading-actions"><input ref="itemImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('items',$event)"><button class="soft" @click="itemImport?.click()">Import Excel</button><button class="soft" @click="exportData('items')">Export Excel</button><button class="primary" @click="openItem()">+ Tambah Barang</button></div></div>
        <section class="panel toolbar"><input v-model="filters.itemSearch" type="search" placeholder="Cari nama atau SKU..."><select v-model="filters.category"><option value="">Semua kategori</option><option v-for="v in data.categories" :value="String(v.id)">{{v.name}}</option></select><select v-model="filters.stock"><option value="">Semua stok</option><option value="empty">Stok habis</option><option value="low">Stok menipis (1-5)</option><option value="ready">Stok tersedia</option></select><button class="soft" @click="Object.assign(filters,{itemSearch:'',category:'',stock:''})">Reset Filter</button></section>
        <DataTable actions :rows="filteredItems" :columns="[['sku','Kode / SKU'],['name','Barang'],['category_name','Kategori'],['unit_name','Satuan'],['stock','Stok'],['cost','Harga Beli','money'],['price','Harga Jual','money']]" @edit="editItem" @delete="removeItem" />
      </template>

      <template v-else-if="active==='customers' || active==='suppliers'">
        <div class="page-heading"><div><h2>{{active==='customers'?'Pelanggan':'Supplier'}}</h2><p>Kelola data {{active==='customers'?'pelanggan dan anggota':'mitra pemasok'}}.</p></div><div class="heading-actions"><input v-if="active==='customers'" ref="customerImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('customers',$event)"><input v-else ref="supplierImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('suppliers',$event)"><button class="soft" @click="active==='customers'?customerImport?.click():supplierImport?.click()">Import Excel</button><button class="soft" @click="exportData(active==='customers'?'customers':'suppliers')">Export Excel</button><button class="primary" @click="openParty(active==='customers'?'customer':'supplier')">+ Tambah {{active==='customers'?'Pelanggan':'Supplier'}}</button></div></div>
        <section class="panel toolbar party-toolbar"><input v-if="active==='customers'" v-model="filters.customerSearch" type="search" placeholder="Cari kode, nama, atau telepon..."><input v-else v-model="filters.supplierSearch" type="search" placeholder="Cari nama, telepon, atau alamat..."></section>
        <DataTable v-if="active==='customers'" actions :rows="filteredCustomers" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon'],['address','Alamat']]" @edit="editParty('customer',$event)" @delete="removeParty('customer',$event)"/><DataTable v-else actions :rows="filteredSuppliers" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon'],['address','Alamat']]" @edit="editParty('supplier',$event)" @delete="removeParty('supplier',$event)"/>
      </template>

      <template v-else-if="active==='sale'||active==='purchase'">
        <form class="panel transaction" @submit.prevent="saveTransaction(active==='sale'?'SALE':'PURCHASE')">
          <div class="section-title"><div><h2>{{editing.transaction?'Edit ':''}}{{active==='sale'?'Transaksi Kasir':'Penerimaan Pembelian'}}</h2><p class="hint">{{editing.transaction?'Perubahan barang otomatis menyesuaikan stok.':active==='sale'?'Gunakan pelanggan UMUM untuk non-anggota. Kurang bayar hanya dapat dicatat dengan metode Piutang.':'Pilih supplier lebih dulu; hanya barang dari supplier tersebut yang dapat ditambahkan.'}}</p></div><button v-if="editing.transaction" type="button" class="soft" @click="resetTransaction()">Batal Edit</button></div>
          <div class="transaction-layout"><div class="transaction-products">
            <label v-if="active==='sale'">Pelanggan<select v-model="transactionForm.customer_id" required><option v-for="v in data.customers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label><label v-else>Supplier<select v-model="transactionForm.supplier_id" required><option :value="null" disabled>Pilih supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label>
            <div class="line-head"><span>Barang</span><span>Jumlah</span><span>Harga Satuan</span><span>Subtotal</span><span></span></div><div class="lines"><div v-for="(line,i) in transactionForm.items" :key="i" class="line"><select v-model="line.item_id" required :disabled="active==='purchase'&&!transactionForm.supplier_id" @change="chooseItem(line)"><option :value="null" disabled>{{active==='purchase'&&!transactionForm.supplier_id?'Pilih supplier dahulu':'Pilih barang'}}</option><option v-for="v in transactionItems" :value="v.id">{{v.sku}} · {{v.name}} (stok {{v.stock}})</option></select><input v-model.number="line.quantity" aria-label="Jumlah barang" type="number" min="1" placeholder="Jumlah" required><input :value="formatNumber(line.unit_price)" @input="setCurrency($event,line,'unit_price')" aria-label="Harga satuan" inputmode="numeric" placeholder="0" required><strong>{{money(line.quantity*line.unit_price)}}</strong><button type="button" class="icon" :disabled="transactionForm.items.length===1" @click="transactionForm.items.splice(i,1)">×</button></div></div>
            <p v-if="active==='purchase'&&transactionForm.supplier_id&&!transactionItems.length" class="empty supplier-empty">Belum ada barang yang terhubung ke supplier ini. Atur supplier pada master Barang dahulu.</p><button type="button" class="soft add-item" :disabled="active==='purchase'&&!transactionForm.supplier_id" @click="addLine">+ Tambah Barang</button><label class="transaction-notes">Catatan<textarea v-model="transactionForm.notes" placeholder="Opsional: catatan transaksi"/></label>
          </div><aside class="checkout-stack"><div class="checkout-label">Ringkasan Transaksi</div><div class="checkout-row grand-total"><span>Grand Total</span><strong>{{money(lineTotal)}}</strong></div><label>Metode Pembayaran<select v-model="transactionForm.payment_method_id" required><option :value="null" disabled>Pilih metode pembayaran</option><option v-for="v in data.payment_methods" :value="v.id">{{v.name}}</option></select></label><label>Pembayaran (Rp)<input :value="formatNumber(transactionForm.paid_amount)" @input="setCurrency($event,transactionForm,'paid_amount')" inputmode="numeric" placeholder="0" required></label><div class="checkout-row" :class="changeAmount<0?'shortage':'change'"><span>{{changeAmount<0?'Kurang Bayar':'Kembalian'}}</span><strong>{{money(Math.abs(changeAmount))}}</strong></div><button type="submit" class="primary" :disabled="!lineTotal||submitting">{{submitting?'Menyimpan…':editing.transaction?'Simpan Perubahan':'Simpan Transaksi'}}</button></aside></div>
        </form>
      </template>

      <section v-else-if="active==='history'" class="panel history">
        <div class="history-note"><strong>Aturan stok transaksi</strong><span>Batalkan penjualan: stok barang kembali. Batalkan pembelian: stok dikurangi dan akan ditolak jika barang sudah terpakai. Transaksi dengan cicilan piutang tidak dapat diedit atau dibatalkan.</span></div>
        <div class="history-filters"><input v-model="filters.historySearch" type="search" placeholder="Cari invoice, pelanggan, supplier, atau catatan..."><select v-model="filters.historyType"><option value="">Semua tipe</option><option value="SALE">Penjualan</option><option value="PURCHASE">Pembelian</option></select><select v-model="filters.historyStatus"><option value="">Semua status</option><option value="ACTIVE">Aktif</option><option value="VOID">Dibatalkan</option><option value="PAID">Lunas</option><option value="PARTIAL">Sebagian</option><option value="UNPAID">Belum bayar</option></select><button type="button" class="soft" @click="Object.assign(filters,{historySearch:'',historyType:'',historyStatus:''})">Reset</button><button type="button" class="soft" @click="exportData('transactions')">Export Histori</button></div>
        <div class="table-wrap"><table><thead><tr><th>Invoice / Tanggal</th><th>Tipe</th><th>Pelanggan / Supplier</th><th>Status</th><th>Total</th><th>Aksi</th></tr></thead><tbody><template v-for="v in filteredTransactions" :key="v.id"><tr :class="{voided:v.status==='VOID'}"><td><strong>{{v.invoice_no}}</strong><small>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</small></td><td>{{v.transaction_type==='SALE'?'Penjualan':'Pembelian'}}</td><td>{{v.customer_name||v.supplier_name||'—'}}</td><td>{{v.status==='VOID'?'Dibatalkan':v.payment_status}}</td><td>{{money(v.grand_total)}}</td><td class="table-actions"><button class="soft" @click="expandedTransaction=expandedTransaction===v.id?null:v.id">{{expandedTransaction===v.id?'Tutup':'Detail'}}</button><button class="soft" @click="printReceipt(v)">Struk PDF</button><button class="soft" :disabled="v.status==='VOID'" @click="editTransaction(v)">Ubah</button><button class="danger" :disabled="v.status==='VOID'" @click="voidTransaction(v)">Batalkan</button></td></tr><tr v-if="expandedTransaction===v.id" class="history-detail"><td colspan="6"><div><span v-for="line in v.items" :key="line.item_id"><b>{{line.item_name}}</b> · {{line.quantity}} × {{money(line.unit_price)}} = {{money(line.subtotal)}}</span></div><div><span>Uang diterima <b>{{money(v.amount_received)}}</b></span><span>Kembalian <b>{{money(v.change_amount)}}</b></span><span v-if="v.notes">Catatan: {{v.notes}}</span><span v-if="v.status==='VOID'">Alasan batal: {{v.void_reason}}</span></div></td></tr></template><tr v-if="!filteredTransactions.length"><td colspan="6" class="empty">Tidak ada transaksi yang cocok</td></tr></tbody></table></div>
      </section>
      <section v-else-if="active==='debts'" class="panel"><h2>Pembayaran Piutang Pelanggan</h2><p class="hint">Piutang dibuat otomatis ketika jumlah yang dibayar di kasir lebih kecil dari grand total. Masukkan nominal cicilan pada transaksi yang sesuai; sisa piutang akan berkurang otomatis.</p><div class="debt" v-for="v in data.debts" :key="v.id"><div><strong>{{v.customer_name}}</strong><small>Invoice {{v.invoice_no}}</small><small>Awal {{money(v.original_amount)}} · Sisa <b>{{money(v.remaining_amount)}}</b></small></div><form v-if="v.status==='OPEN'" @submit.prevent="payDebt(v)"><label>Nominal Pembayaran (Rp)<input :value="formatNumber(debtPayments[v.id])" @input="setCurrency($event,debtPayments,String(v.id))" inputmode="numeric" pattern="[0-9.]+" placeholder="0" required></label><button class="primary" :disabled="!debtPayments[v.id]||debtPayments[v.id]>v.remaining_amount">Catat Pembayaran</button></form><span v-else class="paid">Lunas</span></div><p v-if="!data.debts.length" class="empty">Belum ada piutang pelanggan.</p></section>
      <section v-else-if="active==='masters'" class="panel"><h2>Pengaturan Barang</h2><p class="hint">Kelola pilihan yang muncul pada form barang dan transaksi: kategori untuk mengelompokkan barang, merek untuk produsennya, satuan untuk bentuk stok, dan metode pembayaran untuk kasir.</p><form class="inline" @submit.prevent="saveMaster"><select v-model="masterForm.table" @change="editing.master=null;masterForm.name=''"><option value="categories">Kategori</option><option value="brands">Merek</option><option value="units">Satuan</option><option value="payment_methods">Metode Pembayaran</option></select><input v-model.trim="masterForm.name" minlength="2" maxlength="100" placeholder="Masukkan nama" required><button class="primary">{{editing.master?'Simpan':'Tambah'}}</button></form><div class="master-grid"><article v-for="table in ['categories','brands','units','payment_methods']"><h3>{{({categories:'Kategori',brands:'Merek',units:'Satuan',payment_methods:'Metode Pembayaran'} as any)[table]}}</h3><div class="master-row" v-for="v in data[table]"><span>{{v.name}}</span><button class="mini" @click="editMaster(table,v)">Ubah</button><button class="mini danger" @click="deleteMaster(table,v)">Hapus</button></div></article></div></section>

      <section v-if="selectedReceipt" class="print-receipt" :class="{'print-target':printMode==='receipt'}"><header><h1>KOPERASI</h1><p>{{selectedReceipt.transaction_type==='SALE'?'STRUK PENJUALAN':'BUKTI PEMBELIAN'}}</p></header><div class="receipt-meta"><span>Invoice</span><b>{{selectedReceipt.invoice_no}}</b><span>Tanggal</span><b>{{new Date(selectedReceipt.transaction_date).toLocaleString('id-ID')}}</b><span>{{selectedReceipt.transaction_type==='SALE'?'Pelanggan':'Supplier'}}</span><b>{{selectedReceipt.customer_name||selectedReceipt.supplier_name||'Umum'}}</b><span>Metode</span><b>{{selectedReceipt.payment_method_name||'-'}}</b></div><table><tbody><template v-for="line in selectedReceipt.items" :key="line.item_id"><tr><td colspan="2"><b>{{line.item_name}}</b></td></tr><tr><td>{{line.quantity}} × {{money(line.unit_price)}}</td><td>{{money(line.subtotal)}}</td></tr></template></tbody><tfoot><tr><th>Grand Total</th><th>{{money(selectedReceipt.grand_total)}}</th></tr><tr><td>{{selectedReceipt.transaction_type==='SALE'?'Uang Diterima':'Pembayaran'}}</td><td>{{money(selectedReceipt.amount_received)}}</td></tr><tr v-if="selectedReceipt.change_amount"><td>Kembalian</td><td>{{money(selectedReceipt.change_amount)}}</td></tr><tr v-if="selectedReceipt.payment_status!=='PAID'"><td>Sisa Piutang</td><td>{{money(selectedReceipt.grand_total-selectedReceipt.paid_amount)}}</td></tr></tfoot></table><p v-if="selectedReceipt.notes" class="receipt-notes">Catatan: {{selectedReceipt.notes}}</p><p v-if="selectedReceipt.status==='VOID'" class="receipt-void">TRANSAKSI DIBATALKAN<br>{{selectedReceipt.void_reason}}</p><footer>Terima kasih</footer></section>

      <div v-if="modal" class="modal-backdrop" @mousedown.self="modal==='item'?cancelItem():closeParty(modal)"><section class="modal-card" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editing[modal]?'Ubah':'Tambah'}} {{modal==='item'?'Barang':modal==='customer'?'Pelanggan':'Supplier'}}</h2><p>Lengkapi data berikut, lalu simpan perubahan.</p></div><button class="modal-close" aria-label="Tutup" @click="modal==='item'?cancelItem():closeParty(modal)">×</button></div>
        <form v-if="modal==='item'" class="grid" @submit.prevent="saveItem"><label>Kode / SKU<input v-model.trim="itemForm.sku" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: ATK-001" required></label><label>Nama<input v-model.trim="itemForm.name" minlength="3" maxlength="100" required></label><label>Kategori<select v-model="itemForm.category_id" required><option :value="null" disabled>Pilih kategori</option><option v-for="v in data.categories" :value="v.id">{{v.name}}</option></select></label><label>Merek<input v-model.trim="itemForm.brand_name" minlength="2" maxlength="100" placeholder="Contoh: Lenovo" required></label><label>Satuan<select v-model="itemForm.unit_id" required><option :value="null" disabled>Pilih satuan</option><option v-for="v in data.units" :value="v.id">{{v.name}}</option></select></label><label>Supplier<select v-model="itemForm.supplier_id"><option :value="null">Tanpa supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.name}}</option></select></label><label>Stok awal<input v-model.number="itemForm.stock" type="number" min="0" required></label><label>Harga beli (Rp)<input :value="formatNumber(itemForm.cost)" @input="setCurrency($event,itemForm,'cost')" inputmode="numeric" pattern="[0-9.]+" required></label><label>Harga jual (Rp)<input :value="formatNumber(itemForm.price)" @input="setCurrency($event,itemForm,'price')" inputmode="numeric" pattern="[0-9.]+" required></label><label class="wide">Deskripsi<textarea v-model="itemForm.description" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="cancelItem()">Batal</button><button class="primary">{{editing.item?'Simpan Perubahan':'Simpan Barang'}}</button></div></form>
        <form v-else-if="modal==='customer'" class="grid" @submit.prevent="saveParty('customer')"><label>Kode Anggota<input v-model.trim="customerForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: AGT-001" required></label><label>Nama<input v-model.trim="customerForm.name" minlength="3" maxlength="120" required></label><label>Nomor Telepon<input v-model="customerForm.phone" type="tel" inputmode="numeric" pattern="[0-9]{8,20}" placeholder="Contoh: 081234567890"></label><label class="wide">Alamat<textarea v-model="customerForm.address" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeParty('customer')">Batal</button><button class="primary">{{editing.customer?'Simpan Perubahan':'Simpan Pelanggan'}}</button></div></form>
        <form v-else class="grid" @submit.prevent="saveParty('supplier')"><label>Kode Supplier<input v-model.trim="supplierForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: SUP-001" required></label><label>Nama<input v-model.trim="supplierForm.name" minlength="3" maxlength="100" required></label><label>Nomor Telepon<input v-model="supplierForm.phone" type="tel" inputmode="numeric" pattern="[0-9]{8,20}" placeholder="Contoh: 081234567890" required></label><label class="wide">Alamat<textarea v-model="supplierForm.address" minlength="5" required/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeParty('supplier')">Batal</button><button class="primary">{{editing.supplier?'Simpan Perubahan':'Simpan Supplier'}}</button></div></form>
      </section></div>
      <div v-if="userModal" class="modal-backdrop" @mousedown.self="closeUser"><section class="modal-card user-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editingUser?'Ubah':'Tambah'}} Pengguna</h2><p>Password saat edit boleh dikosongkan jika tidak ingin diganti.</p></div><button class="modal-close" aria-label="Tutup" @click="closeUser">×</button></div><form class="grid" @submit.prevent="saveUser"><label>Nama<input v-model.trim="userForm.name" minlength="2" maxlength="100" required></label><label>Email<input v-model.trim="userForm.email" type="email" required></label><label>Password<input v-model="userForm.password" type="password" minlength="8" :required="!editingUser" autocomplete="new-password"></label><label>Role<select v-model="userForm.role" :disabled="String(editingUser)===String(currentUser.id)"><option value="admin">Admin</option><option value="cashier">Kasir</option><option value="viewer">Viewer</option></select><small v-if="String(editingUser)===String(currentUser.id)">Role akun sendiri tidak dapat diubah.</small></label><label class="check-label"><input v-model="userForm.active" type="checkbox" :disabled="String(editingUser)===String(currentUser.id)"> Akun aktif</label><div class="modal-actions wide"><button type="button" class="soft" @click="closeUser">Batal</button><button class="primary">Simpan</button></div></form></section></div>
    </main>
  </div>
</template>
