package database

import (
	"context"
	"fmt"

	"go-pos-playground/internal/config"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func New(ctx context.Context, cfg config.Config) (*pgxpool.Pool, error) {
	dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",
		cfg.DBHost,
		cfg.DBPort,
		cfg.DBUser,
		cfg.DBPassword,
		cfg.DBName,
		cfg.DBSSLMode,
	)

	db, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(ctx); err != nil {
		db.Close()
		return nil, err
	}

	return db, nil
}

// Migrate applies each schema version exactly once. Version 1 adopts both new
// and pre-existing databases because its statements are intentionally idempotent.
func Migrate(ctx context.Context, db *pgxpool.Pool, schema string) error {
	if schema == "" {
		return fmt.Errorf("DB_SCHEMA must not be empty")
	}

	qualifiedSchema := pgx.Identifier{schema}.Sanitize()
	tx, err := db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin database migration: %w", err)
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtext($1))`, "go-pos-migration:"+schema); err != nil {
		return fmt.Errorf("lock database migrations: %w", err)
	}
	if _, err := tx.Exec(ctx, fmt.Sprintf(`CREATE SCHEMA IF NOT EXISTS %s`, qualifiedSchema)); err != nil {
		return fmt.Errorf("create migration schema: %w", err)
	}
	if _, err := tx.Exec(ctx, fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.schema_migrations (
		version BIGINT PRIMARY KEY,
		name VARCHAR(200) NOT NULL,
		applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	)`, qualifiedSchema)); err != nil {
		return fmt.Errorf("create migration ledger: %w", err)
	}
	statements := []string{
		fmt.Sprintf(`CREATE SCHEMA IF NOT EXISTS %s`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL,
			email VARCHAR(255) NOT NULL,
			password_hash TEXT NOT NULL,
			role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'cashier', 'viewer')),
			active BOOLEAN NOT NULL DEFAULT TRUE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON %s.users (LOWER(email))`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.auth_sessions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL REFERENCES %s.users(id) ON DELETE CASCADE,
			token_hash VARCHAR(64) NOT NULL UNIQUE,
			expires_at TIMESTAMPTZ NOT NULL,
			revoked_at TIMESTAMPTZ,
			replaced_by_hash VARCHAR(64),
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS auth_sessions_user_id_idx ON %s.auth_sessions (user_id)`, qualifiedSchema),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON %s.auth_sessions (expires_at)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.audit_logs (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL,
			user_name VARCHAR(100) NOT NULL,
			user_email VARCHAR(255) NOT NULL,
			action VARCHAR(30) NOT NULL,
			entity_type VARCHAR(50) NOT NULL,
			entity_id VARCHAR(100) NOT NULL DEFAULT '',
			method VARCHAR(10) NOT NULL,
			path TEXT NOT NULL,
			status_code INTEGER NOT NULL,
			ip_address VARCHAR(64) NOT NULL DEFAULT '',
			user_agent TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.audit_logs ADD COLUMN IF NOT EXISTS user_name VARCHAR(100) NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.audit_logs ADD COLUMN IF NOT EXISTS user_email VARCHAR(255) NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.audit_logs ALTER COLUMN entity_id TYPE VARCHAR(1000)`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.audit_logs a
			SET user_name=CASE WHEN a.user_name='' THEN u.name ELSE a.user_name END,
				user_email=CASE WHEN a.user_email='' THEN u.email ELSE a.user_email END
			FROM %s.users u
			WHERE u.id=a.user_id AND (a.user_name='' OR a.user_email='')`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_user_id_fkey`, qualifiedSchema),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx ON %s.audit_logs (created_at DESC)`, qualifiedSchema),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS audit_logs_user_id_idx ON %s.audit_logs (user_id)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.suppliers (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL,
			phone VARCHAR(50) NOT NULL,
			address TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			deleted_at TIMESTAMPTZ
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.items (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			supplier_id BIGINT REFERENCES %s.suppliers(id),
			name VARCHAR(100) NOT NULL,
			description TEXT NOT NULL DEFAULT '',
			stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
			price BIGINT NOT NULL DEFAULT 0 CHECK (price >= 0),
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			deleted_at TIMESTAMPTZ
		)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS supplier_id BIGINT`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS price BIGINT NOT NULL DEFAULT 0`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.suppliers ADD COLUMN IF NOT EXISTS code VARCHAR(50)`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.suppliers SET code='SUP-' || LPAD(id::text, 3, '0') WHERE code IS NULL OR BTRIM(code)=''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.suppliers ALTER COLUMN code SET NOT NULL`, qualifiedSchema),
		fmt.Sprintf(`CREATE UNIQUE INDEX IF NOT EXISTS suppliers_code_unique ON %s.suppliers (code)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.categories (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL UNIQUE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.brands (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL UNIQUE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.units (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(50) NOT NULL UNIQUE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.customers (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			code VARCHAR(50) NOT NULL UNIQUE,
			name VARCHAR(120) NOT NULL,
			customer_type VARCHAR(20) NOT NULL DEFAULT 'NON_MEMBER' CHECK (customer_type IN ('MEMBER', 'NON_MEMBER')),
			phone VARCHAR(50) NOT NULL DEFAULT '',
			address TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			deleted_at TIMESTAMPTZ
		)`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.payment_methods (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(50) NOT NULL UNIQUE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS sku VARCHAR(50)`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.items SET sku='BRG-' || LPAD(id::text, 3, '0') WHERE sku IS NULL OR BTRIM(sku)=''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ALTER COLUMN sku SET NOT NULL`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES %s.categories(id)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES %s.brands(id)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS unit_id BIGINT REFERENCES %s.units(id)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS cost BIGINT NOT NULL DEFAULT 0 CHECK (cost >= 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS base_unit_id BIGINT REFERENCES %s.units(id)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS units_per_package INTEGER NOT NULL DEFAULT 1 CHECK (units_per_package > 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS allow_retail BOOLEAN NOT NULL DEFAULT FALSE`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS retail_cost BIGINT NOT NULL DEFAULT 0 CHECK (retail_cost >= 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.items ADD COLUMN IF NOT EXISTS retail_price BIGINT NOT NULL DEFAULT 0 CHECK (retail_price >= 0)`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.items SET base_unit_id=unit_id WHERE base_unit_id IS NULL`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.items SET retail_cost=cost,retail_price=price WHERE units_per_package=1 AND retail_cost=0 AND retail_price=0`, qualifiedSchema),
		// Soft-deleted items must not reserve their SKU forever.
		fmt.Sprintf(`DROP INDEX IF EXISTS %s.items_sku_unique`, qualifiedSchema),
		fmt.Sprintf(`CREATE UNIQUE INDEX IF NOT EXISTS items_active_sku_unique ON %s.items (sku) WHERE sku IS NOT NULL AND deleted_at IS NULL`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.transactions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			invoice_no VARCHAR(50) NOT NULL UNIQUE,
			transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('SALE', 'PURCHASE')),
			transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			customer_id BIGINT REFERENCES %s.customers(id),
			supplier_id BIGINT REFERENCES %s.suppliers(id),
			payment_method_id BIGINT REFERENCES %s.payment_methods(id),
			payment_status VARCHAR(20) NOT NULL DEFAULT 'PAID' CHECK (payment_status IN ('PAID', 'UNPAID', 'PARTIAL')),
			grand_total BIGINT NOT NULL CHECK (grand_total >= 0),
			paid_amount BIGINT NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
			notes TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema, qualifiedSchema, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.transaction_items (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			transaction_id BIGINT NOT NULL REFERENCES %s.transactions(id) ON DELETE CASCADE,
			item_id BIGINT NOT NULL REFERENCES %s.items(id),
			quantity INTEGER NOT NULL CHECK (quantity > 0),
			unit_price BIGINT NOT NULL CHECK (unit_price >= 0),
			subtotal BIGINT NOT NULL CHECK (subtotal >= 0)
		)`, qualifiedSchema, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transaction_items ADD COLUMN IF NOT EXISTS unit_id BIGINT REFERENCES %s.units(id)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transaction_items ADD COLUMN IF NOT EXISTS unit_name VARCHAR(50) NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transaction_items ADD COLUMN IF NOT EXISTS conversion_factor INTEGER NOT NULL DEFAULT 1 CHECK (conversion_factor > 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transaction_items ADD COLUMN IF NOT EXISTS base_quantity INTEGER NOT NULL DEFAULT 1 CHECK (base_quantity > 0)`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.transaction_items ti SET unit_id=i.unit_id,unit_name=COALESCE(u.name,''),base_quantity=ti.quantity,conversion_factor=1 FROM %s.items i LEFT JOIN %s.units u ON u.id=i.unit_id WHERE ti.item_id=i.id AND (ti.unit_id IS NULL OR ti.unit_name='')`, qualifiedSchema, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS amount_received BIGINT NOT NULL DEFAULT 0 CHECK (amount_received >= 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS change_amount BIGINT NOT NULL DEFAULT 0 CHECK (change_amount >= 0)`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','VOID'))`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS void_reason TEXT NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ`, qualifiedSchema),
		fmt.Sprintf(`UPDATE %s.transactions SET amount_received=paid_amount WHERE amount_received=0 AND paid_amount>0`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.debts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			transaction_id BIGINT NOT NULL UNIQUE REFERENCES %s.transactions(id),
			customer_id BIGINT NOT NULL REFERENCES %s.customers(id),
			original_amount BIGINT NOT NULL CHECK (original_amount > 0),
			remaining_amount BIGINT NOT NULL CHECK (remaining_amount >= 0),
			status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'PAID')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.debt_payments (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			debt_id BIGINT NOT NULL REFERENCES %s.debts(id),
			amount BIGINT NOT NULL CHECK (amount > 0),
			payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			notes TEXT NOT NULL DEFAULT ''
		)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.debt_payments ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.debt_payments ADD COLUMN IF NOT EXISTS reversal_reason TEXT NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.debt_payments ADD COLUMN IF NOT EXISTS reversed_by_user_id BIGINT`, qualifiedSchema),
		fmt.Sprintf(`ALTER TABLE %s.debt_payments ADD COLUMN IF NOT EXISTS reversed_by_name VARCHAR(100) NOT NULL DEFAULT ''`, qualifiedSchema),
		fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s.stock_movements (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			item_id BIGINT NOT NULL REFERENCES %s.items(id),
			movement_type VARCHAR(30) NOT NULL,
			quantity_before INTEGER NOT NULL,
			quantity_change INTEGER NOT NULL,
			quantity_after INTEGER NOT NULL,
			notes TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)`, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`
			INSERT INTO %s.stock_movements(item_id,movement_type,quantity_before,quantity_change,quantity_after,notes)
			SELECT i.id,'OPENING_BALANCE',0,i.stock,i.stock,'Saldo stok saat histori mulai digunakan'
			FROM %s.items i
			WHERE i.stock<>0 AND NOT EXISTS (SELECT 1 FROM %s.stock_movements m WHERE m.item_id=i.id)
		`, qualifiedSchema, qualifiedSchema, qualifiedSchema),
		fmt.Sprintf(`INSERT INTO %s.categories (name) VALUES ('Umum') ON CONFLICT (name) DO NOTHING`, qualifiedSchema),
		fmt.Sprintf(`INSERT INTO %s.brands (name) VALUES ('Tanpa Merek') ON CONFLICT (name) DO NOTHING`, qualifiedSchema),
		fmt.Sprintf(`INSERT INTO %s.units (name) VALUES ('Pcs'), ('Pack'), ('Box') ON CONFLICT (name) DO NOTHING`, qualifiedSchema),
		fmt.Sprintf(`INSERT INTO %s.payment_methods (name) VALUES ('Tunai'), ('Transfer'), ('Piutang') ON CONFLICT (name) DO NOTHING`, qualifiedSchema),
		fmt.Sprintf(`INSERT INTO %s.customers (code, name, customer_type) VALUES ('UMUM', 'Umum / Non Member', 'NON_MEMBER') ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name`, qualifiedSchema),
	}

	type migration struct {
		version int64
		name    string
		up      func() error
	}
	migrations := []migration{{
		version: 1,
		name:    "baseline schema",
		up: func() error {
			for index, statement := range statements {
				if _, err := tx.Exec(ctx, statement); err != nil {
					return fmt.Errorf("statement %d: %w", index+1, err)
				}
			}
			var hasSupplierForeignKey bool
			if err := tx.QueryRow(ctx, `
				SELECT EXISTS (
					SELECT 1 FROM pg_constraint c
					JOIN pg_class t ON t.oid=c.conrelid
					JOIN pg_namespace n ON n.oid=t.relnamespace
					WHERE n.nspname=$1 AND t.relname='items' AND c.conname='items_supplier_id_fkey'
				)
			`, schema).Scan(&hasSupplierForeignKey); err != nil {
				return fmt.Errorf("check items supplier foreign key: %w", err)
			}
			if !hasSupplierForeignKey {
				if _, err := tx.Exec(ctx, fmt.Sprintf(
					`ALTER TABLE %s.items ADD CONSTRAINT items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES %s.suppliers(id)`,
					qualifiedSchema, qualifiedSchema,
				)); err != nil {
					return fmt.Errorf("add items supplier foreign key: %w", err)
				}
			}
			return nil
		},
	}, {
		version: 2,
		name:    "transaction invoice sequence",
		up: func() error {
			sequence := fmt.Sprintf("%s.invoice_number_seq", qualifiedSchema)
			if _, err := tx.Exec(ctx, fmt.Sprintf(`CREATE SEQUENCE IF NOT EXISTS %s`, sequence)); err != nil {
				return fmt.Errorf("create invoice sequence: %w", err)
			}
			if _, err := tx.Exec(ctx, fmt.Sprintf(`
				SELECT setval($1::regclass, GREATEST(COALESCE(MAX(id), 0) + 1, 1), false)
				FROM %s.transactions
			`, qualifiedSchema), sequence); err != nil {
				return fmt.Errorf("initialize invoice sequence: %w", err)
			}
			return nil
		},
	}, {
		version: 3,
		name:    "transaction idempotency",
		up: func() error {
			statements := []string{
				fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128)`, qualifiedSchema),
				fmt.Sprintf(`ALTER TABLE %s.transactions ADD COLUMN IF NOT EXISTS request_hash CHAR(64)`, qualifiedSchema),
				fmt.Sprintf(`CREATE UNIQUE INDEX IF NOT EXISTS transactions_idempotency_key_unique ON %s.transactions(idempotency_key) WHERE idempotency_key IS NOT NULL`, qualifiedSchema),
			}
			for _, statement := range statements {
				if _, err := tx.Exec(ctx, statement); err != nil {
					return err
				}
			}
			return nil
		},
	}, {
		version: 4,
		name:    "asynchronous payments and stock reservations",
		up: func() error {
			statements := []string{
				fmt.Sprintf(`CREATE TABLE %s.payments (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					transaction_id BIGINT NOT NULL UNIQUE REFERENCES %s.transactions(id),
					provider VARCHAR(30) NOT NULL,
					external_reference VARCHAR(100) NOT NULL UNIQUE,
					status VARCHAR(20) NOT NULL CHECK(status IN ('PENDING','PAID','FAILED','EXPIRED')),
					amount BIGINT NOT NULL CHECK(amount > 0),
					paid_at TIMESTAMPTZ,
					expires_at TIMESTAMPTZ NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
					updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
				)`, qualifiedSchema, qualifiedSchema),
				fmt.Sprintf(`CREATE TABLE %s.stock_reservations (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					payment_id BIGINT NOT NULL REFERENCES %s.payments(id),
					item_id BIGINT NOT NULL REFERENCES %s.items(id),
					quantity INTEGER NOT NULL CHECK(quantity > 0),
					status VARCHAR(20) NOT NULL CHECK(status IN ('ACTIVE','FULFILLED','RELEASED','EXPIRED')),
					expires_at TIMESTAMPTZ NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
				)`, qualifiedSchema, qualifiedSchema, qualifiedSchema),
				fmt.Sprintf(`CREATE INDEX stock_reservations_active_item_idx ON %s.stock_reservations(item_id) WHERE status='ACTIVE'`, qualifiedSchema),
				fmt.Sprintf(`INSERT INTO %s.payment_methods(name) VALUES('QRIS Dummy') ON CONFLICT(name) DO NOTHING`, qualifiedSchema),
			}
			for _, statement := range statements {
				if _, err := tx.Exec(ctx, statement); err != nil {
					return err
				}
			}
			return nil
		},
	}}

	for _, migration := range migrations {
		var applied bool
		if err := tx.QueryRow(ctx, fmt.Sprintf(`SELECT EXISTS(SELECT 1 FROM %s.schema_migrations WHERE version=$1)`, qualifiedSchema), migration.version).Scan(&applied); err != nil {
			return fmt.Errorf("read database migration v%d: %w", migration.version, err)
		}
		if applied {
			continue
		}
		if err := migration.up(); err != nil {
			return fmt.Errorf("run database migration v%d (%s): %w", migration.version, migration.name, err)
		}
		if _, err := tx.Exec(ctx, fmt.Sprintf(`INSERT INTO %s.schema_migrations(version,name) VALUES($1,$2)`, qualifiedSchema), migration.version, migration.name); err != nil {
			return fmt.Errorf("record database migration v%d: %w", migration.version, err)
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit database migrations: %w", err)
	}
	return nil
}
