<script setup lang="ts">
const props=defineProps<{rows:any[],columns:any[][],actions?:boolean,voidActions?:boolean,selectable?:boolean}>()
defineEmits(['edit','delete','void'])
const sorting = defineModel<string>('sorting', { required: true })
const selectedIds = defineModel<number[]>('selectedIds', { default:()=>[] })
const selectableRows=computed(()=>props.rows.filter((row:any)=>row.code!=='UMUM'))
const allSelected=computed(()=>selectableRows.value.length>0&&selectableRows.value.every((row:any)=>selectedIds.value.includes(Number(row.id))))
function toggleAll(){const pageIds=selectableRows.value.map((row:any)=>Number(row.id));selectedIds.value=allSelected.value?selectedIds.value.filter(id=>!pageIds.includes(id)):[...new Set([...selectedIds.value,...pageIds])]}
function toggle(id:number){selectedIds.value=selectedIds.value.includes(id)?selectedIds.value.filter(value=>value!==id):[...selectedIds.value,id]}
const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const display=(row:any,col:any[])=>col[2]==='money'?money(row[col[0]]):col[2]==='date'?new Date(row[col[0]]).toLocaleString('id-ID'):row[col[0]]??'—'
</script>
<template><section class="panel"><div class="table-wrap"><table><thead><tr><th v-if="selectable" class="selection-cell"><input type="checkbox" :checked="allSelected" aria-label="Pilih semua data pada halaman" @change="toggleAll"></th><SortableTh v-for="c in columns" :key="c[0]" v-model="sorting" :field="c[0]" :default-direction="c[4]||'asc'" :class="c[3]">{{c[1]}}</SortableTh><th v-if="actions||voidActions" class="table-center">Aksi</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id" :class="{voided:row.status==='VOID',selected:selectable&&selectedIds.includes(Number(row.id))}"><td v-if="selectable" class="selection-cell"><input type="checkbox" :checked="selectedIds.includes(Number(row.id))" :disabled="row.code==='UMUM'" :aria-label="`Pilih ${row.name||row.code}`" @change="toggle(Number(row.id))"></td><td v-for="c in columns" :class="c[3]">{{display(row,c)}}</td><td v-if="actions" class="table-actions"><button class="soft" :disabled="row.code==='UMUM'" @click="$emit('edit',row)">Ubah</button><button class="danger" :disabled="row.code==='UMUM'" @click="$emit('delete',row)">Hapus</button></td><td v-if="voidActions" class="table-actions"><button class="danger" :disabled="row.status==='VOID'" :title="row.void_reason||''" @click="$emit('void',row)">{{row.status==='VOID'?'Dibatalkan':'Batalkan'}}</button></td></tr><tr v-if="!rows.length"><td :colspan="columns.length+((actions||voidActions)?1:0)+(selectable?1:0)" class="empty">Belum ada data</td></tr></tbody></table></div></section></template>
