<script setup lang="ts">
import Swal from 'sweetalert2'
import DebtRow from './DebtRow.vue'
import StockMovementHistory from './StockMovementHistory.vue'

const route = useRoute()

const api = useKoperasiApi()
const currentUser = ref<any>(null)
const authReady = ref(false)
const loginError = ref('')
const loginForm = reactive({ email:'', password:'' })
const { formatNumber, setCurrency } = useCurrencyInput()
const { downloadExcel, downloadWorkbook, parseExcel } = useExcelData()
const allNav = [
  ['dashboard', 'Dashboard', '/'], ['items', 'Barang', '/barang'], ['customers', 'Pelanggan', '/pelanggan'], ['suppliers', 'Supplier', '/supplier'],
  ['sale', 'Kasir', '/kasir'], ['purchase', 'Pembelian', '/pembelian'], ['history', 'Histori', '/histori'], ['debts', 'Piutang', '/piutang'], ['masters', 'Pengaturan Barang', '/pengaturan'], ['users', 'Pengguna', '/pengguna'], ['audit', 'Audit Log', '/audit'],
]
const nav = computed(()=>allNav.filter(([, , path])=>isUIRouteAllowed(path, currentUser.value?.role || '')))
const routeKey = () => allNav.find((item)=>item[2]===route.path)?.[0] || 'dashboard'
const active = ref(routeKey())
const loading = ref(false)
const submitting = ref(false)
const error = ref('')
const notice = ref('')
const undoSnackbar=reactive<{visible:boolean,message:string,busy:boolean,restore:null|(()=>Promise<any>),reload:Array<()=>Promise<void>>}>({visible:false,message:'',busy:false,restore:null,reload:[]})
let undoTimer:ReturnType<typeof setTimeout>|null=null
const data = reactive<any>({ dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[],users:[],auditLogs:[] })
const editing = reactive<any>({ item:null, customer:null, supplier:null, master:null, transaction:null })
const printMode = ref<null|'monthly'|'receipt'>(null)
const modal = ref<null|'item'|'customer'|'supplier'>(null)
const filters = reactive({ itemSearch:'', category:'', stock:'', customerSearch:'', supplierSearch:'', historySearch:'', historyType:'', historyStatus:'', auditSearch:'', auditAction:'' })
const sorting = reactive({
  items:'name:asc', customers:'name:asc', suppliers:'name:asc',
  transactions:'transaction_date:desc', users:'name:asc', daily:'date:asc', audit:'created_at:desc',
})
const money = (v:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const { dashboardYear,dashboardMonth,years,months,maxSales,monthlyReportTransactions,monthlyReportTotal,dashboardPeriods,dailyTotals,loadDashboard } = useDashboard(api,data)
const { masterForm,loadMasters,openMaster,saveMaster,editMaster,deleteMaster,findOrCreateMaster } = useMasters({api,data,editing,submit,reloadItems:()=>loadItems()})
const { itemForm,itemImport,filteredItems,stockHistoryItem,stockMovements,loadItems,saveItem,openItem,editItem,cancelItem,removeItem,restoreDeletedItem,openStockHistory,closeStockHistory } = useItems({api,data,filters,editing,modal,submit,softDelete,findOrCreateMaster})
const { transactionForm,transactionContext,expandedTransaction,selectedReceipt,lineTotal,changeAmount,isAsyncPayment,transactionItems,filteredTransactions,loadTransactions,voidTransaction,simulatePendingPayment,paymentCountdown,paymentStatusLabel,addLine,resetTransaction,editTransaction,saveTransaction,availableUnits,chooseUnit,chooseItem,stockLabel,printReceipt } = useTransactions({api,data,active,editing,filters,submit,reloadDashboard:()=>loadDashboard(),reloadItems:()=>loadItems(),reloadDebts:()=>loadDebts(),money,printDocument})
const { debtPayments,paymentHistories,expandedDebt,loadDebts,payDebt,togglePaymentHistory,reversePayment } = useDebts({api,data,submit,reloadDashboard:()=>loadDashboard(),reloadTransactions:()=>loadTransactions()})
const { customerForm,customerImport,filteredCustomers,loadCustomers,saveCustomer,openCustomer,editCustomer,closeCustomer,removeCustomer,restoreDeletedCustomer } = useCustomers({api,data,transactionForm,filters,editing,modal,submit,softDelete})
const { supplierForm,supplierImport,filteredSuppliers,loadSuppliers,saveSupplier,openSupplier,editSupplier,closeSupplier,removeSupplier,restoreDeletedSupplier } = useSuppliers({api,data,filters,editing,modal,submit,softDelete})
const { userForm,userModal,editingUser,loadUsers,openUser,closeUser,saveUser,removeUser } = useUsers({api,data,currentUser,submit})
const sortedItems = useSorting<any>(filteredItems, () => sorting.items)
const sortedCustomers = useSorting<any>(filteredCustomers, () => sorting.customers)
const sortedSuppliers = useSorting<any>(filteredSuppliers, () => sorting.suppliers)
const sortableTransactions = computed(() => filteredTransactions.value.map((transaction:any) => ({
  ...transaction,
  party_name: transaction.customer_name || transaction.supplier_name || '',
})))
const sortedTransactions = useSorting<any>(sortableTransactions, () => sorting.transactions)
const sortedUsers = useSorting<any>(() => data.users, () => sorting.users)
const sortedDaily = useSorting<any>(() => data.dashboard.daily || [], () => sorting.daily)
const filteredAuditLogs = computed(() => data.auditLogs.filter((entry:any) => {
  const query = filters.auditSearch.toLowerCase()
  const matchesSearch = !query || [entry.user_name,entry.user_email,entry.entity_type,entry.path].some(value => String(value||'').toLowerCase().includes(query))
  return matchesSearch && (!filters.auditAction || entry.action === filters.auditAction)
}))
const sortedAuditLogs = useSorting<any>(filteredAuditLogs, () => sorting.audit)
const bulkSelected=reactive<{items:number[],customers:number[],suppliers:number[]}>({items:[],customers:[],suppliers:[]})
const selectedDebts=ref<number[]>([])
const debtView=ref<'open'|'paid'>('open')
const bulkLabels={items:'barang',customers:'pelanggan',suppliers:'supplier'} as const
const bulkLoaders={items:loadItems,customers:loadCustomers,suppliers:loadSuppliers}
const deletedLoaders={items:api.deletedItems,customers:api.deletedCustomers,suppliers:api.deletedSuppliers}
const escapeHTML=(value:any)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]||char))
const bulkMessage=(result:any,label:string)=>{const rows=result?.results||[];const success=rows.filter((row:any)=>row.success).length;return`${success} ${label} berhasil, ${rows.length-success} gagal diproses`}
async function bulkDeleteSelected(kind:keyof typeof bulkSelected){const ids=bulkSelected[kind];if(!ids.length)return;const label=bulkLabels[kind];const result=await Swal.fire({icon:'warning',title:`Hapus ${ids.length} ${label}?`,text:'Seluruh data terpilih akan dipindahkan ke data terhapus.',showCancelButton:true,confirmButtonText:'Ya, hapus',cancelButtonText:'Batal',confirmButtonColor:'#b8322a'});if(!result.isConfirmed)return;let message='';const done=await submit(async()=>{message=bulkMessage(await api.bulkDelete(kind,ids),label)},()=>message,[bulkLoaders[kind]]);if(done)bulkSelected[kind]=[]}
async function bulkRestoreDeleted(kind:keyof typeof bulkSelected){const rows=await deletedLoaders[kind]();const label=bulkLabels[kind];if(!rows.length){await Swal.fire({icon:'info',title:`Tidak ada ${label} terhapus`});return}const options=rows.map((row:any)=>`<label class="bulk-restore-option"><input type="checkbox" value="${Number(row.id)}"><span>${escapeHTML(`${row.sku||row.code} · ${row.name}`)}</span></label>`).join('');const result=await Swal.fire({title:`Pulihkan beberapa ${label}`,width:'min(720px, calc(100vw - 32px))',html:`<label class="bulk-restore-all"><input id="bulk-restore-all" type="checkbox"><span>Pilih semua</span></label><div id="bulk-restore-list" class="bulk-restore-list">${options}</div>`,didOpen:()=>{const all=document.getElementById('bulk-restore-all') as HTMLInputElement|null;all?.addEventListener('change',()=>document.querySelectorAll<HTMLInputElement>('#bulk-restore-list input').forEach(input=>{input.checked=Boolean(all.checked)}))},showCancelButton:true,confirmButtonText:'Pulihkan pilihan',cancelButtonText:'Batal',preConfirm:()=>{const ids=Array.from(document.querySelectorAll<HTMLInputElement>('#bulk-restore-list input:checked')).map(input=>Number(input.value));if(!ids.length){Swal.showValidationMessage('Pilih minimal satu data');return false}return ids}});if(!result.isConfirmed||!result.value)return;let message='';await submit(async()=>{message=bulkMessage(await api.bulkRestore(kind,result.value),label)},()=>message,[bulkLoaders[kind]])}
async function bulkResetSelectedStock(){const ids=bulkSelected.items;if(!ids.length)return;const total=data.items.filter((item:any)=>ids.includes(Number(item.id))).reduce((sum:number,item:any)=>sum+Number(item.stock||0),0);const result=await Swal.fire({icon:'warning',title:`Reset stok ${ids.length} barang?`,text:`Total ${total} unit stok akan diubah menjadi 0 dan dicatat ke pergerakan stok.`,showCancelButton:true,confirmButtonText:'Ya, reset stok',cancelButtonText:'Batal',confirmButtonColor:'#b8322a'});if(!result.isConfirmed)return;let message='';const done=await submit(async()=>{message=bulkMessage(await api.bulkResetStock(ids),'barang')},()=>message,[loadItems,loadDashboard]);if(done)bulkSelected.items=[]}
async function bulkSettleSelectedDebts(){const ids=selectedDebts.value;if(!ids.length)return;const debts=data.debts.filter((debt:any)=>ids.includes(Number(debt.id))&&debt.status==='OPEN');const total=debts.reduce((sum:number,debt:any)=>sum+Number(debt.remaining_amount||0),0);const result=await Swal.fire({icon:'question',title:`Lunasi ${debts.length} piutang?`,text:`Pembayaran sebesar ${money(total)} akan dicatat pada histori masing-masing piutang.`,showCancelButton:true,confirmButtonText:'Ya, lunasi semua',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!result.isConfirmed)return;let message='';const done=await submit(async()=>{message=bulkMessage(await api.bulkSettleDebts(ids),'piutang')},()=>message,[loadDebts,loadDashboard,loadTransactions]);if(done)selectedDebts.value=[]}
const itemPage = reactive(usePagination<any>(sortedItems))
const customerPage = reactive(usePagination<any>(sortedCustomers))
const supplierPage = reactive(usePagination<any>(sortedSuppliers))
const transactionPage = reactive(usePagination<any>(sortedTransactions))
const visibleDebts=computed(()=>data.debts.filter((debt:any)=>debtView.value==='open'?debt.status==='OPEN':debt.status==='PAID'))
const debtPage = reactive(usePagination<any>(visibleDebts))
watch(debtView,()=>{selectedDebts.value=[];debtPage.setPage(1)})
function toggleAllOpenDebts(){const ids=debtPage.pageItems.filter((debt:any)=>debt.status==='OPEN').map((debt:any)=>Number(debt.id));const all=ids.length>0&&ids.every((id:number)=>selectedDebts.value.includes(id));selectedDebts.value=all?selectedDebts.value.filter(id=>!ids.includes(id)):[...new Set([...selectedDebts.value,...ids])]}
const userPage = reactive(usePagination<any>(sortedUsers))
const auditPage = reactive(usePagination<any>(sortedAuditLogs, 20))

const jakartaDateTime = (value:string) => new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value))

async function runLoaders(loaders:Array<()=>Promise<void>>){loading.value=true;error.value='';try{await Promise.all(loaders.map(loader=>loader()))}catch(e:any){error.value=e?.data?.message||e.message||'Gagal memuat data'}finally{loading.value=false}}
async function loadActiveRoute(){
  const loaders:Record<string,Array<()=>Promise<void>>>={
    dashboard:[loadDashboard,loadTransactions,loadDebts],items:[loadItems,loadSuppliers,loadMasters],customers:[loadCustomers],suppliers:[loadSuppliers],
    sale:[loadItems,loadCustomers,loadMasters],purchase:[loadItems,loadSuppliers,loadMasters],history:[loadTransactions],debts:[loadDebts],masters:[loadMasters],users:[loadUsers],audit:[async()=>{data.auditLogs=await api.auditLogs()}],
  }
  await runLoaders(loaders[active.value]||loaders.dashboard)
}
async function submit(action:()=>Promise<any>, message:string|(()=>string), reload:Array<()=>Promise<void>>, confirmation:string|false=false){if(submitting.value)return false;if(confirmation!==false){const result=await Swal.fire({icon:'question',title:'Konfirmasi',text:confirmation,showCancelButton:true,confirmButtonText:'Ya, simpan',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!result.isConfirmed)return false}error.value='';notice.value='';submitting.value=true;try{await action();await runLoaders(reload);await Swal.fire({icon:'success',title:'Berhasil',text:typeof message==='function'?message():message,confirmButtonColor:'#1d6b43'});return true}catch(e:any){const message=e?.data?.message||e.message||'Gagal menyimpan data';await Swal.fire({icon:'error',title:'Gagal',text:message,confirmButtonColor:'#1d6b43'});return false}finally{submitting.value=false}}
function closeUndoSnackbar(){if(undoTimer)clearTimeout(undoTimer);undoTimer=null;undoSnackbar.visible=false;undoSnackbar.restore=null;undoSnackbar.reload=[]}
async function softDelete(remove:()=>Promise<any>,restore:()=>Promise<any>,message:string,reload:Array<()=>Promise<void>>){if(submitting.value)return false;closeUndoSnackbar();submitting.value=true;try{await remove();await runLoaders(reload);Object.assign(undoSnackbar,{visible:true,message,busy:false,restore,reload});undoTimer=setTimeout(closeUndoSnackbar,8000);return true}catch(e:any){await Swal.fire({icon:'error',title:'Gagal',text:e?.data?.message||e.message||'Data gagal dihapus',confirmButtonColor:'#1d6b43'});return false}finally{submitting.value=false}}
async function undoSoftDelete(){if(!undoSnackbar.restore||undoSnackbar.busy)return;undoSnackbar.busy=true;if(undoTimer)clearTimeout(undoTimer);try{await undoSnackbar.restore();await runLoaders(undoSnackbar.reload);closeUndoSnackbar();await Swal.fire({icon:'success',title:'Dibatalkan',text:'Data berhasil dipulihkan.',timer:1400,showConfirmButton:false})}catch(e:any){undoSnackbar.busy=false;undoTimer=setTimeout(closeUndoSnackbar,8000);await Swal.fire({icon:'error',title:'Tidak dapat memulihkan',text:e?.data?.message||e.message||'Kode atau SKU mungkin sudah digunakan data aktif',confirmButtonColor:'#1d6b43'})}}
onBeforeUnmount(closeUndoSnackbar)
watch(()=>route.path,async()=>{const next=routeKey();if(next===active.value)return;active.value=next;if(currentUser.value)await loadActiveRoute()})
watch(active,(next)=>{error.value='';notice.value='';modal.value=null;if((next==='sale'||next==='purchase')&&transactionContext.value!==next){resetTransaction(next);transactionContext.value=next}})
watch(dashboardYear,()=>runLoaders([loadDashboard]))
watch(dashboardMonth,()=>runLoaders([loadDashboard]))
function blockInvalidNumber(event:KeyboardEvent){const target=event.target as HTMLInputElement;if(target?.type==='number'&&['e','E','+','-','.'].includes(event.key))event.preventDefault()}
function sanitizeNumeric(event:Event){const target=event.target as HTMLInputElement;if(target?.type==='tel')target.value=target.value.replace(/\D/g,'')}
async function exportData(kind:'items'|'customers'|'suppliers'|'transactions'){
  const date=new Date().toISOString().slice(0,10)
  if(kind==='items')await downloadExcel(`barang-${date}.xlsx`,['sku','name','description','supplier_code','category','brand','package_unit','base_unit','units_per_package','allow_retail','stock_display','available_retail_quantity','package_cost','package_price','retail_cost','retail_price'],data.items.map((v:any)=>[v.sku,v.name,v.description,data.suppliers.find((s:any)=>s.id===v.supplier_id)?.code||'',v.category_name||'',v.brand_name||'',v.unit_name||'',v.base_unit_name||'',v.units_per_package,v.allow_retail?'yes':'no',v.stock_display,v.stock,v.cost,v.price,v.retail_cost,v.retail_price]))
  if(kind==='customers')await downloadExcel(`pelanggan-${date}.xlsx`,['code','name','phone','address'],data.customers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='suppliers')await downloadExcel(`supplier-${date}.xlsx`,['code','name','phone','address'],data.suppliers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='transactions')await downloadExcel(`histori-transaksi-${date}.xlsx`,['invoice','date','type','party','status','payment_status','total','received','change','items','notes'],filteredTransactions.value.map((v:any)=>[v.invoice_no,v.transaction_date,v.transaction_type,v.customer_name||v.supplier_name||'',v.status,v.payment_status,v.grand_total,v.amount_received,v.change_amount,v.items.map((x:any)=>`${x.item_name} (${x.quantity} ${x.unit_name} x ${x.unit_price})`).join('; '),v.notes]))
}
async function login(){loginError.value='';submitting.value=true;try{const result=await api.login(loginForm.email,loginForm.password);api.token.value=result.access_token;currentUser.value=result.user;loginForm.password='';active.value='dashboard';await runLoaders([loadDashboard,loadTransactions,loadDebts]);await navigateTo('/')}catch(e:any){loginError.value=e?.data?.message||'Login gagal'}finally{submitting.value=false}}
async function logout(){try{await api.logout()}finally{api.token.value=null;currentUser.value=null;Object.assign(data,{dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[]});await navigateTo('/login')}}
function sameText(a:any,b:any){return String(a??'').trim()===String(b??'').trim()}
function sameCode(a:any,b:any){return String(a??'').trim().toLowerCase()===String(b??'').trim().toLowerCase()}
async function importData(kind:'items'|'customers'|'suppliers',event:Event){
  const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return
  try{
    const rows=await parseExcel(file);if(!rows.length)throw new Error('Excel kosong atau formatnya tidak sesuai template export.')
    const confirm=await Swal.fire({icon:'question',title:`Import ${rows.length} baris?`,text:'Data dengan kode yang sama akan diperbarui.',showCancelButton:true,confirmButtonText:'Ya, import',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!confirm.isConfirmed)return
    submitting.value=true
    let created=0,updated=0,skipped=0
    const knownCustomers=[...data.customers],knownSuppliers=[...data.suppliers],knownItems=[...data.items]
    for(let index=0;index<rows.length;index++){
      const row:any=rows[index]
      try{
        if(kind==='customers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi');if(String(row.code).toUpperCase()==='UMUM'){skipped++;continue}
          const existing=knownCustomers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateCustomer(existing.id,body):api.createCustomer(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownCustomers.push({...body,id:null})
        }else if(kind==='suppliers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi')
          const existing=knownSuppliers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateSupplier(existing.id,body):api.createSupplier(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownSuppliers.push({...body,id:null})
        }else{
          if(!row.sku||!row.name)throw new Error('sku dan name wajib diisi')
          const supplier=row.supplier_code?data.suppliers.find((v:any)=>v.code.toLowerCase()===row.supplier_code.toLowerCase()):null;if(row.supplier_code&&!supplier)throw new Error(`supplier ${row.supplier_code} tidak ditemukan`)
          const packageUnit=row.package_unit||row.unit;const baseUnit=row.base_unit||packageUnit;const factor=Math.max(1,Number(row.units_per_package||1));const allowRetail=['yes','true','1','ya'].includes(String(row.allow_retail||'').toLowerCase())
          const body={sku:row.sku,name:row.name,description:row.description||'',supplier_id:supplier?.id||null,category_id:await findOrCreateMaster('categories',data.categories,row.category),brand_id:await findOrCreateMaster('brands',data.brands,row.brand),unit_id:await findOrCreateMaster('units',data.units,packageUnit),base_unit_id:await findOrCreateMaster('units',data.units,baseUnit),units_per_package:factor,allow_retail:factor>1&&allowRetail,stock:Number(row.available_retail_quantity??row.stock_base??row.stock??0),cost:Number(row.package_cost??row.cost??0),price:Number(row.package_price??row.price??0),retail_cost:Number(row.retail_cost??row.package_cost??row.cost??0),retail_price:Number(row.retail_price??row.package_price??row.price??0)}
          const identical=knownItems.find((v:any)=>sameText(v.name,body.name)&&Number(v.supplier_id||0)===Number(body.supplier_id||0)&&Number(v.unit_id||0)===Number(body.unit_id||0)&&Number(v.base_unit_id||0)===Number(body.base_unit_id||0)&&Number(v.units_per_package||1)===Number(body.units_per_package||1)&&Boolean(v.allow_retail)===Boolean(body.allow_retail)&&Number(v.price||0)===Number(body.price||0)&&Number(v.retail_price||0)===Number(body.retail_price||0))
          if(identical){skipped++;continue}
          const existing=knownItems.find((v:any)=>sameCode(v.sku,row.sku));if(existing&&!existing.id)throw new Error(`sku ${row.sku} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateItem(existing.id,body):api.createItem(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownItems.push({...body,id:null})
        }
      }catch(e:any){throw new Error(`Baris ${index+2}: ${e?.data?.message||e.message}`)}
    }
    await runLoaders(kind==='items'?[loadItems,loadMasters]:kind==='customers'?[loadCustomers]:[loadSuppliers]);await Swal.fire({icon:'success',title:'Import selesai',text:`${created} dibuat, ${updated} diperbarui, ${skipped} dilewati.`,confirmButtonColor:'#1d6b43'})
  }catch(e:any){await Swal.fire({icon:'error',title:'Import gagal',text:e.message||'File tidak dapat diproses.',confirmButtonColor:'#1d6b43'})}finally{submitting.value=false;input.value=''}
}
async function printDocument(mode:'monthly'|'receipt'){printMode.value=mode;await nextTick();window.print();printMode.value=null}
function printMonthlyReport(){printDocument('monthly')}
async function exportMonthlyReport(){
  const prompt=await Swal.fire({title:'Export laporan bulanan',input:'textarea',inputLabel:'Catatan (opsional)',inputPlaceholder:'Tambahkan catatan untuk sheet laporan…',showCancelButton:true,confirmButtonText:'Export Excel',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!prompt.isConfirmed)return
  const transactionRows=(values:any[])=>values.map(v=>[v.invoice_no,jakartaDateTime(v.transaction_date),v.customer_name||v.supplier_name||'',v.payment_method_name||'',v.payment_status,v.status,v.grand_total,v.paid_amount,v.notes||'',v.items.map((x:any)=>`${x.item_name} (${x.quantity} ${x.unit_name} x ${x.unit_price})`).join('; ')])
  const sheets:any[]=[
    {name:'Ringkasan Bulanan',columns:['Metrik','Nilai'],rows:[['Periode',`${months[dashboardMonth.value-1]} ${dashboardYear.value}`],['Total pemasukan',dailyTotals.value.income],['Total pengeluaran',dailyTotals.value.expense],['Piutang dibuat',dailyTotals.value.debt],['Pendapatan bersih',dailyTotals.value.net_income],['Jumlah transaksi penjualan',monthlyReportTransactions.value.length]]},
    {name:'Penjualan Harian',columns:['Tanggal','Pemasukan','Pengeluaran','Piutang','Pendapatan Bersih'],rows:(data.dashboard.daily||[]).map((v:any)=>[v.date,v.income,v.expense,v.debt,v.net_income]).concat([['TOTAL',dailyTotals.value.income,dailyTotals.value.expense,dailyTotals.value.debt,dailyTotals.value.net_income]])},
    {name:'Riwayat Penjualan',columns:['Invoice','Tanggal WIB','Pelanggan','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='SALE'))},
    {name:'Riwayat Pembelian',columns:['Invoice','Tanggal WIB','Supplier','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='PURCHASE'))},
    {name:'Piutang',columns:['Invoice','Pelanggan','Nilai Awal','Sisa','Status','Tanggal WIB'],rows:data.debts.map((v:any)=>[v.invoice_no,v.customer_name,v.original_amount,v.remaining_amount,v.status,jakartaDateTime(v.created_at)])},
  ];if(String(prompt.value||'').trim())sheets.push({name:'Catatan',columns:['Catatan','Dibuat pada'],rows:[[String(prompt.value).trim(),jakartaDateTime(new Date().toISOString())]]})
  await downloadWorkbook(`laporan-${dashboardYear.value}-${String(dashboardMonth.value).padStart(2,'0')}.xlsx`,sheets)
}
onMounted(async()=>{try{if(api.token.value){currentUser.value=await api.me();if(route.path==='/login'){active.value='dashboard';await runLoaders([loadDashboard,loadTransactions,loadDebts]);await navigateTo('/')}else await loadActiveRoute()}else if(route.path!=='/login')await navigateTo('/login')}catch{api.token.value=null;currentUser.value=null;if(route.path!=='/login')await navigateTo('/login')}finally{authReady.value=true}})
</script>

<template>
  <section v-if="authReady&&!currentUser" class="login-page"><form class="login-card" @submit.prevent="login"><div class="login-mark">K</div><h1>Masuk ke Koperasi</h1><p>Gunakan akun yang diberikan administrator.</p><label>Email<input v-model.trim="loginForm.email" type="email" autocomplete="username" required></label><label>Password<input v-model="loginForm.password" type="password" autocomplete="current-password" required></label><p v-if="loginError" class="alert error">{{loginError}}</p><button class="primary" :disabled="submitting">{{submitting?'Memproses…':'Masuk'}}</button></form></section>
  <div v-else-if="currentUser" class="app-shell">
    <aside><div class="brand"><span>K</span><div><strong>Koperasi</strong><small>Operational Console</small></div></div><nav><NuxtLink v-for="n in nav" :key="n[0]" :to="n[2]" :class="{active:active===n[0]}">{{ n[1] }}</NuxtLink></nav></aside>
    <main @keydown="blockInvalidNumber" @input="sanitizeNumeric">
      <StockMovementHistory v-if="stockHistoryItem" :item="stockHistoryItem" :movements="stockMovements" @close="closeStockHistory"/>
      <header><div><p class="eyebrow">SIG KOPERASI · GO + NUXT</p><h1>{{ nav.find(n=>n[0]===active)?.[1] }}</h1></div><div class="user-actions"><span><b>{{currentUser.name}}</b><small>{{currentUser.role}}</small></span><button class="soft" @click="logout">Keluar</button></div></header>
      <p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p>

      <section v-if="active==='audit'" class="panel"><div class="page-heading"><div><h2>Audit Log</h2><p>Riwayat perubahan data dan aksi pengguna. Isi request sensitif tidak disimpan.</p></div><div class="heading-actions"><PageSizeSelect v-model="auditPage.pageSize" @update:model-value="auditPage.setPage(1)"/><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button></div></div><div class="history-filters audit-filters"><input v-model="filters.auditSearch" type="search" placeholder="Cari pengguna, modul, atau path..."><select v-model="filters.auditAction"><option value="">Semua aksi</option><option value="CREATE">Tambah</option><option value="UPDATE">Ubah</option><option value="DELETE">Hapus</option><option value="VOID">Batalkan transaksi</option><option value="PAYMENT">Pembayaran</option></select><button class="soft" @click="Object.assign(filters,{auditSearch:'',auditAction:''})">Reset</button></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.audit" field="created_at" default-direction="desc">Waktu</SortableTh><SortableTh v-model="sorting.audit" field="user_name">Pengguna</SortableTh><th>Email</th><SortableTh v-model="sorting.audit" field="action">Aksi</SortableTh><SortableTh v-model="sorting.audit" field="entity_type">Modul / ID</SortableTh><SortableTh v-model="sorting.audit" field="status_code" class="table-center">Hasil</SortableTh><th>Alamat IP</th></tr></thead><tbody><tr v-for="entry in auditPage.pageItems" :key="entry.id"><td>{{jakartaDateTime(entry.created_at)}}</td><td><strong>{{entry.user_name}}</strong></td><td>{{entry.user_email}}</td><td><span class="role-badge">{{entry.action}}</span><small>{{entry.method}} {{entry.path}}</small></td><td>{{entry.entity_type}}<small v-if="entry.entity_id">ID {{entry.entity_id}}</small></td><td class="table-center" :class="entry.status_code<400?'income':'expense'">{{entry.status_code<400?'Berhasil':'Ditolak'}} · {{entry.status_code}}</td><td>{{entry.ip_address||'—'}}</td></tr><tr v-if="!auditPage.totalItems"><td colspan="7" class="empty">Belum ada aktivitas yang cocok.</td></tr></tbody></table></div><PaginationControls v-bind="auditPage" @update:page="auditPage.setPage"/></section>
      <section v-else-if="active==='users'" class="panel"><div class="page-heading"><div><h2>Daftar Pengguna</h2><p>Kelola akun dan hak akses aplikasi.</p></div><div class="heading-actions"><PageSizeSelect v-model="userPage.pageSize" @update:model-value="userPage.setPage(1)"/><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="openUser()">+ Tambah Pengguna</button></div></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.users" field="name">Nama</SortableTh><SortableTh v-model="sorting.users" field="email">Email</SortableTh><SortableTh v-model="sorting.users" field="role" class="table-center">Role</SortableTh><SortableTh v-model="sorting.users" field="active" default-direction="desc" class="table-center">Status</SortableTh><th class="table-center">Aksi</th></tr></thead><tbody><tr v-for="user in userPage.pageItems" :key="user.id"><td><b>{{user.name}}</b><small v-if="String(user.id)===String(currentUser.id)"> · akun Anda</small></td><td>{{user.email}}</td><td class="table-center"><span class="role-badge">{{user.role}}</span></td><td class="table-center">{{user.active?'Aktif':'Nonaktif'}}</td><td class="table-actions"><button class="soft" @click="openUser(user)">Ubah</button><button class="danger" :disabled="String(user.id)===String(currentUser.id)" @click="removeUser(user)">Hapus</button></td></tr></tbody></table></div><PaginationControls v-bind="userPage" @update:page="userPage.setPage"/></section>
      <template v-else-if="active==='dashboard'">
        <section class="panel dashboard-toolbar"><div><strong>Periode Laporan</strong><small>Ringkasan bulan dan tahun mengikuti pilihan ini.</small></div><select v-model.number="dashboardMonth"><option v-for="(month,i) in months" :value="i+1">{{month}}</option></select><select v-model.number="dashboardYear"><option v-for="year in years" :value="year">{{year}}</option></select><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="exportMonthlyReport">Export Laporan Excel</button></section>
        <section class="period-stats"><article v-for="period in dashboardPeriods"><div><small>{{period.label}}</small><b>Pemasukan</b><strong class="income">{{money(period.value.income)}}</strong></div><div><b>Pengeluaran</b><strong class="expense">{{money(period.value.expense)}}</strong></div><div><b>Piutang Dibuat</b><strong>{{money(period.value.debt)}}</strong></div></article></section>
        <section class="operational-stats"><span>Piutang terbuka <b>{{money(data.dashboard.open_debt)}}</b></span><span>Payment pending <b>{{data.dashboard.pending_payments||0}}</b></span><span>Stok menipis <b>{{data.dashboard.low_stock_items||0}} barang</b></span><span>Total barang <b>{{data.dashboard.total_items||0}}</b></span><span>Pelanggan <b>{{data.dashboard.total_customers||0}}</b></span></section>
        <section class="panel chart-panel"><div class="section-title"><div><h2>Grafik Penjualan {{dashboardYear}}</h2><small>Total nilai transaksi penjualan per bulan</small></div></div><div class="chart"><div v-for="(value,i) in data.dashboard.monthly_sales||[]" :key="Number(i)" class="bar-column"><strong>{{value?money(value):'Rp0'}}</strong><div class="bar-track"><span :style="{height:`${Math.max((value/maxSales)*100,value?4:0)}%`}"></span></div><small>{{months[Number(i)]}}</small></div></div></section>
        <section class="panel daily-report"><div class="section-title"><div><h2>Rekap Harian {{months[dashboardMonth-1]}} {{dashboardYear}}</h2><small>Perhitungan tanggal menggunakan zona waktu Asia/Jakarta (UTC+7).</small></div></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.daily" field="date">Tanggal</SortableTh><SortableTh v-model="sorting.daily" field="income" default-direction="desc">Total Pemasukan</SortableTh><SortableTh v-model="sorting.daily" field="expense" default-direction="desc">Total Pengeluaran</SortableTh><SortableTh v-model="sorting.daily" field="debt" default-direction="desc">Total Piutang</SortableTh><SortableTh v-model="sorting.daily" field="net_income" default-direction="desc">Total Pendapatan</SortableTh></tr></thead><tbody><tr v-for="row in sortedDaily" :key="row.date"><td>{{new Date(`${row.date}T00:00:00+07:00`).toLocaleDateString(`id-ID`,{weekday:`long`,day:`2-digit`,month:`short`,timeZone:`Asia/Jakarta`})}}</td><td>{{money(row.income)}}</td><td>{{money(row.expense)}}</td><td>{{money(row.debt)}}</td><td :class="row.net_income<0?`expense`:`income`">{{money(row.net_income)}}</td></tr></tbody><tfoot><tr><th>TOTAL</th><th>{{money(dailyTotals.income)}}</th><th>{{money(dailyTotals.expense)}}</th><th>{{money(dailyTotals.debt)}}</th><th>{{money(dailyTotals.net_income)}}</th></tr></tfoot></table></div></section>
        <section class="print-report" :class="{'print-target':printMode==='monthly'}"><h1>Laporan Penjualan Bulanan</h1><p>Periode: {{months[dashboardMonth-1]}} {{dashboardYear}}</p><table><thead><tr><th>Tanggal</th><th>Invoice</th><th>Pelanggan</th><th>Total</th></tr></thead><tbody><tr v-for="v in monthlyReportTransactions"><td>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</td><td>{{v.invoice_no}}</td><td>{{v.customer_name||'Umum'}}</td><td>{{money(v.grand_total)}}</td></tr><tr v-if="!monthlyReportTransactions.length"><td colspan="4">Tidak ada transaksi penjualan.</td></tr></tbody><tfoot><tr><th colspan="3">Total Penjualan</th><th>{{money(monthlyReportTotal)}}</th></tr></tfoot></table></section>
      </template>

      <template v-else-if="active==='items'">
        <div class="page-heading"><div><h2>Daftar Barang</h2><p>Kelola katalog dan persediaan barang.</p></div><div class="heading-actions"><input ref="itemImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('items',$event)"><button class="soft" @click="itemImport?.click()">Import Excel</button><button class="soft" @click="exportData('items')">Export Excel</button><button class="soft" @click="restoreDeletedItem">Pulihkan Satu</button><button class="soft" @click="bulkRestoreDeleted('items')">Pulihkan Massal</button><button v-if="bulkSelected.items.length" class="soft" @click="bulkResetSelectedStock">Reset Stok {{bulkSelected.items.length}}</button><button v-if="bulkSelected.items.length" class="danger" @click="bulkDeleteSelected('items')">Hapus {{bulkSelected.items.length}} Terpilih</button><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="openItem()">+ Tambah Barang</button></div></div>
        <section class="panel toolbar"><PageSizeSelect v-model="itemPage.pageSize" @update:model-value="itemPage.setPage(1)"/><input v-model="filters.itemSearch" type="search" placeholder="Cari nama atau SKU..."><select v-model="filters.category"><option value="">Semua kategori</option><option v-for="v in data.categories" :value="String(v.id)">{{v.name}}</option></select><select v-model="filters.stock"><option value="">Semua stok</option><option value="empty">Stok habis</option><option value="low">Stok menipis (1-5)</option><option value="ready">Stok tersedia</option></select><button class="soft" @click="Object.assign(filters,{itemSearch:'',category:'',stock:''})">Reset Filter</button></section>
        <DataTable v-model:sorting="sorting.items" v-model:selected-ids="bulkSelected.items" selectable actions trace-actions :rows="itemPage.pageItems" :columns="[['sku','Kode / SKU'],['name','Barang'],['category_name','Kategori'],['unit_name','Kemasan'],['base_unit_name','Eceran'],['stock_display','Stok',null,'table-center'],['cost','Harga Beli/Kemasan','money','table-center','desc'],['price','Harga Jual/Kemasan','money','table-center','desc']]" @trace="openStockHistory" @edit="editItem" @delete="removeItem" />
        <PaginationControls v-bind="itemPage" @update:page="itemPage.setPage"/>
      </template>

      <template v-else-if="active==='customers' || active==='suppliers'">
        <div class="page-heading"><div><h2>Daftar {{active==='customers'?'Pelanggan':'Supplier'}}</h2><p>Kelola data {{active==='customers'?'pelanggan dan anggota':'mitra pemasok'}}.</p></div><div class="heading-actions"><input v-if="active==='customers'" ref="customerImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('customers',$event)"><input v-else ref="supplierImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('suppliers',$event)"><button class="soft" @click="active==='customers'?customerImport?.click():supplierImport?.click()">Import Excel</button><button class="soft" @click="exportData(active==='customers'?'customers':'suppliers')">Export Excel</button><button class="soft" @click="active==='customers'?restoreDeletedCustomer():restoreDeletedSupplier()">Pulihkan Satu</button><button class="soft" @click="bulkRestoreDeleted(active==='customers'?'customers':'suppliers')">Pulihkan Massal</button><button v-if="bulkSelected[active==='customers'?'customers':'suppliers'].length" class="danger" @click="bulkDeleteSelected(active==='customers'?'customers':'suppliers')">Hapus {{bulkSelected[active==='customers'?'customers':'suppliers'].length}} Terpilih</button><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="active==='customers'?openCustomer():openSupplier()">+ Tambah {{active==='customers'?'Pelanggan':'Supplier'}}</button></div></div>
        <section class="panel toolbar party-toolbar"><PageSizeSelect v-if="active==='customers'" v-model="customerPage.pageSize" @update:model-value="customerPage.setPage(1)"/><PageSizeSelect v-else v-model="supplierPage.pageSize" @update:model-value="supplierPage.setPage(1)"/><input v-if="active==='customers'" v-model="filters.customerSearch" type="search" placeholder="Cari kode, nama, atau telepon..."><input v-else v-model="filters.supplierSearch" type="search" placeholder="Cari nama, telepon, atau alamat..."></section>
        <template v-if="active==='customers'"><DataTable v-model:sorting="sorting.customers" v-model:selected-ids="bulkSelected.customers" selectable actions :rows="customerPage.pageItems" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon',null,'table-center'],['address','Alamat']]" @edit="editCustomer" @delete="removeCustomer"/><PaginationControls v-bind="customerPage" @update:page="customerPage.setPage"/></template><template v-else><DataTable v-model:sorting="sorting.suppliers" v-model:selected-ids="bulkSelected.suppliers" selectable actions :rows="supplierPage.pageItems" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon',null,'table-center'],['address','Alamat']]" @edit="editSupplier" @delete="removeSupplier"/><PaginationControls v-bind="supplierPage" @update:page="supplierPage.setPage"/></template>
      </template>

      <template v-else-if="active==='sale'||active==='purchase'">
        <form class="panel transaction" @submit.prevent="saveTransaction(active==='sale'?'SALE':'PURCHASE')">
          <div class="section-title"><div><h2>{{editing.transaction?'Edit ':''}}{{active==='sale'?'Transaksi Kasir':'Penerimaan Pembelian'}}</h2><p class="hint">{{editing.transaction?'Perubahan barang otomatis menyesuaikan stok.':active==='sale'?'Gunakan pelanggan UMUM untuk non-anggota. Kurang bayar hanya dapat dicatat dengan metode Piutang.':'Pilih supplier lebih dulu; hanya barang dari supplier tersebut yang dapat ditambahkan.'}}</p></div><div class="heading-actions"><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh Data'}}</button><button v-if="editing.transaction" type="button" class="soft" @click="resetTransaction()">Batal Edit</button></div></div>
          <div class="transaction-layout"><div class="transaction-products">
            <label v-if="active==='sale'">Pelanggan<select v-model="transactionForm.customer_id" required><option v-for="v in data.customers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label><label v-else>Supplier<select v-model="transactionForm.supplier_id" required><option :value="null" disabled>Pilih supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label>
            <div class="line-head"><span>Barang</span><span>Satuan</span><span>Jumlah</span><span>Harga/Satuan</span><span>Subtotal</span><span></span></div><div class="lines"><div v-for="(line,i) in transactionForm.items" :key="i" class="line"><select v-model="line.item_id" required :disabled="active==='purchase'&&!transactionForm.supplier_id" @change="chooseItem(line)"><option :value="null" disabled>{{active==='purchase'&&!transactionForm.supplier_id?'Pilih supplier dahulu':'Pilih barang'}}</option><option v-for="v in transactionItems" :value="v.id">{{v.sku}} · {{v.name}} (stok {{stockLabel(v)}})</option></select><select v-model="line.unit_id" required :disabled="!line.item_id" @change="chooseUnit(line)"><option v-for="unit in availableUnits(line)" :value="unit.id">{{unit.name}} ({{unit.factor}} {{data.items.find((v:any)=>v.id===Number(line.item_id))?.base_unit_name||unit.name}})</option></select><input v-model.number="line.quantity" aria-label="Jumlah barang" type="number" min="1" placeholder="Jumlah" required><input :value="formatNumber(line.unit_price)" @input="setCurrency($event,line,'unit_price')" aria-label="Harga satuan" inputmode="numeric" placeholder="0" required><strong>{{money(line.quantity*line.unit_price)}}</strong><button type="button" class="icon" :disabled="transactionForm.items.length===1" @click="transactionForm.items.splice(i,1)">×</button></div></div>
            <p v-if="active==='purchase'&&transactionForm.supplier_id&&!transactionItems.length" class="empty supplier-empty">Belum ada barang yang terhubung ke supplier ini. Atur supplier pada master Barang dahulu.</p><button type="button" class="soft add-item" :disabled="active==='purchase'&&!transactionForm.supplier_id" @click="addLine">+ Tambah Barang</button><label class="transaction-notes">Catatan<textarea v-model="transactionForm.notes" placeholder="Opsional: catatan transaksi"/></label>
          </div><aside class="checkout-stack"><div class="checkout-label">Ringkasan Transaksi</div><div class="checkout-row grand-total"><span>Grand Total</span><strong>{{money(lineTotal)}}</strong></div><label>Metode Pembayaran<select v-model="transactionForm.payment_method_id" required><option :value="null" disabled>Pilih metode pembayaran</option><option v-for="v in data.payment_methods" :value="v.id">{{v.name}}</option></select></label><label>Pembayaran (Rp)<input :value="formatNumber(isAsyncPayment?0:transactionForm.paid_amount)" :disabled="isAsyncPayment" @input="setCurrency($event,transactionForm,'paid_amount')" inputmode="numeric" placeholder="0" required></label><p v-if="isAsyncPayment" class="hint">Stok tersedia akan direservasi sampai countdown payment dummy berakhir.</p><div v-else class="checkout-row" :class="changeAmount<0?'shortage':'change'"><span>{{changeAmount<0?'Kurang Bayar':'Kembalian'}}</span><strong>{{money(Math.abs(changeAmount))}}</strong></div><button type="submit" class="primary" :disabled="!lineTotal||submitting">{{submitting?'Menyimpan…':editing.transaction?'Simpan Perubahan':isAsyncPayment?'Buat QRIS Dummy':'Simpan Transaksi'}}</button></aside></div>
        </form>
      </template>

      <section v-else-if="active==='history'" class="panel history">
        <div class="history-note"><strong>Aturan stok transaksi</strong><span>Batalkan penjualan: stok barang kembali. Batalkan pembelian: stok dikurangi dan akan ditolak jika barang sudah terpakai. Transaksi dengan cicilan piutang tidak dapat diedit atau dibatalkan.</span></div>
        <div class="history-filters"><PageSizeSelect v-model="transactionPage.pageSize" @update:model-value="transactionPage.setPage(1)"/><input v-model="filters.historySearch" type="search" placeholder="Cari invoice, pelanggan, supplier, atau catatan..."><select v-model="filters.historyType"><option value="">Semua tipe</option><option value="SALE">Penjualan</option><option value="PURCHASE">Pembelian</option></select><select v-model="filters.historyStatus"><option value="">Semua status</option><option value="ACTIVE">Aktif</option><option value="VOID">Dibatalkan</option><option value="PAID">Lunas</option><option value="PARTIAL">Sebagian</option><option value="UNPAID">Belum bayar</option></select><button type="button" class="soft" @click="Object.assign(filters,{historySearch:'',historyType:'',historyStatus:''})">Reset</button><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button type="button" class="soft" @click="exportData('transactions')">Export Histori</button></div>
        <div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.transactions" field="transaction_date" default-direction="desc">Invoice / Tanggal</SortableTh><SortableTh v-model="sorting.transactions" field="transaction_type" class="table-center">Tipe</SortableTh><SortableTh v-model="sorting.transactions" field="party_name">Pelanggan / Supplier</SortableTh><SortableTh v-model="sorting.transactions" field="payment_status" class="table-center">Status</SortableTh><SortableTh v-model="sorting.transactions" field="grand_total" default-direction="desc" class="table-center">Total</SortableTh><th class="table-center">Aksi</th></tr></thead><tbody><template v-for="v in transactionPage.pageItems" :key="v.id"><tr :class="{voided:v.status==='VOID'}"><td><strong>{{v.invoice_no}}</strong><small>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</small></td><td class="table-center">{{v.transaction_type==='SALE'?'Penjualan':'Pembelian'}}</td><td>{{v.customer_name||v.supplier_name||'—'}}</td><td class="table-center">{{v.payment?paymentStatusLabel(v):(v.status==='VOID'?'Dibatalkan':v.payment_status)}}</td><td class="table-center">{{money(v.grand_total)}}</td><td class="table-actions"><button class="soft" @click="expandedTransaction=expandedTransaction===v.id?null:v.id">{{expandedTransaction===v.id?'Tutup':'Detail'}}</button><button v-if="v.payment?.status==='PENDING'" class="primary" @click="simulatePendingPayment(v)">Simulasikan</button><button class="soft" @click="printReceipt(v)">Struk PDF</button><button class="soft" :disabled="v.status==='VOID'||!!v.payment" @click="editTransaction(v)">Ubah</button><button class="danger" :disabled="v.status==='VOID'||!!v.payment" @click="voidTransaction(v)">Batalkan</button></td></tr><tr v-if="expandedTransaction===v.id" class="history-detail"><td colspan="6"><div><span v-for="line in v.items" :key="`${line.item_id}-${line.unit_id}`"><b>{{line.item_name}}</b> · {{line.quantity}} {{line.unit_name}} × {{money(line.unit_price)}} = {{money(line.subtotal)}}</span></div><div><span v-if="v.payment">Referensi <b>{{v.payment.external_reference}}</b></span><span v-if="v.payment?.status==='PENDING'">Sisa reservasi <b>{{paymentCountdown(v)}}</b></span><span>Uang diterima <b>{{money(v.amount_received)}}</b></span><span>Kembalian <b>{{money(v.change_amount)}}</b></span><span v-if="v.notes">Catatan: {{v.notes}}</span><span v-if="v.status==='VOID'">Alasan batal: {{v.void_reason}}</span></div></td></tr></template><tr v-if="!transactionPage.totalItems"><td colspan="6" class="empty">Tidak ada transaksi yang cocok</td></tr></tbody></table></div>
        <PaginationControls v-bind="transactionPage" @update:page="transactionPage.setPage"/>
      </section>
      <section v-else-if="active==='debts'" class="panel">
        <h2>Pembayaran Piutang Pelanggan</h2>
        <p class="hint">Pilih beberapa piutang untuk pelunasan massal, catat cicilan, atau koreksi pembayaran dari historinya.</p>
        <div class="debt-tabs">
          <button :class="{active:debtView==='open'}" @click="debtView='open'">Piutang</button>
          <button :class="{active:debtView==='paid'}" @click="debtView='paid'">Piutang Lunas</button>
        </div>
        <div class="list-toolbar debt-toolbar" :class="{'is-sticky':selectedDebts.length}">
          <div class="debt-bulk-actions">
            <PageSizeSelect v-model="debtPage.pageSize" @update:model-value="debtPage.setPage(1)"/>
            <template v-if="debtView==='open'">
              <button class="soft" @click="toggleAllOpenDebts">Pilih Semua</button>
              <button v-if="selectedDebts.length" class="primary" @click="bulkSettleSelectedDebts">Lunasi {{selectedDebts.length}} Terpilih</button>
            </template>
          </div>
          <button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button>
        </div>
        <DebtRow
          v-for="v in debtPage.pageItems"
          :key="v.id"
          :debt="v"
          :selected-debts="selectedDebts"
          :payment-amount="debtPayments[v.id] || 0"
          :expanded="expandedDebt === v.id"
          :payments="paymentHistories[v.id] || []"
          :money="money"
          :format-number="formatNumber"
          @update:selected-debts="selectedDebts=$event"
          @update:payment-amount="debtPayments[v.id]=$event"
          @pay="payDebt(v)"
          @toggle-history="togglePaymentHistory(v)"
          @reverse="reversePayment(v,$event)"
        />
        <p v-if="!debtPage.totalItems" class="empty">{{debtView==='open'?'Tidak ada piutang terbuka.':'Belum ada piutang yang lunas.'}}</p>
        <PaginationControls v-bind="debtPage" @update:page="debtPage.setPage"/>
      </section>
      <section v-else-if="active==='masters'" class="panel"><h2>Master Data Barang</h2><p class="hint">Kelola pilihan yang muncul pada form barang dan transaksi: kategori untuk mengelompokkan barang, merek untuk produsennya, satuan untuk bentuk stok, dan metode pembayaran untuk kasir.</p><form class="inline" @submit.prevent="saveMaster"><select v-model="masterForm.table" @change="editing.master=null;masterForm.name=''"><option value="categories">Kategori</option><option value="brands">Merek</option><option value="units">Satuan</option><option value="payment_methods">Metode Pembayaran</option></select><input v-model.trim="masterForm.name" minlength="2" maxlength="100" placeholder="Masukkan nama" required><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary">{{editing.master?'Simpan':'Tambah'}}</button></form><div class="master-grid"><article v-for="table in ['categories','brands','units','payment_methods']"><h3>{{({categories:'Kategori',brands:'Merek',units:'Satuan',payment_methods:'Metode Pembayaran'} as any)[table]}}</h3><div class="master-row" v-for="v in data[table]"><span>{{v.name}}</span><button class="mini" @click="editMaster(table,v)">Ubah</button><button class="mini danger" @click="deleteMaster(table,v)">Hapus</button></div></article></div></section>

      <section v-if="selectedReceipt" class="print-receipt" :class="{'print-target':printMode==='receipt'}"><header><h1>KOPERASI</h1><p>{{selectedReceipt.transaction_type==='SALE'?'STRUK PENJUALAN':'BUKTI PEMBELIAN'}}</p></header><div class="receipt-meta"><span>Invoice</span><b>{{selectedReceipt.invoice_no}}</b><span>Tanggal</span><b>{{new Date(selectedReceipt.transaction_date).toLocaleString('id-ID')}}</b><span>{{selectedReceipt.transaction_type==='SALE'?'Pelanggan':'Supplier'}}</span><b>{{selectedReceipt.customer_name||selectedReceipt.supplier_name||'Umum'}}</b><span>Metode</span><b>{{selectedReceipt.payment_method_name||'-'}}</b></div><table><tbody><template v-for="line in selectedReceipt.items" :key="`${line.item_id}-${line.unit_id}`"><tr><td colspan="2"><b>{{line.item_name}}</b></td></tr><tr><td>{{line.quantity}} {{line.unit_name}} × {{money(line.unit_price)}}</td><td>{{money(line.subtotal)}}</td></tr></template></tbody><tfoot><tr><th>Grand Total</th><th>{{money(selectedReceipt.grand_total)}}</th></tr><tr><td>{{selectedReceipt.transaction_type==='SALE'?'Uang Diterima':'Pembayaran'}}</td><td>{{money(selectedReceipt.amount_received)}}</td></tr><tr v-if="selectedReceipt.change_amount"><td>Kembalian</td><td>{{money(selectedReceipt.change_amount)}}</td></tr><tr v-if="selectedReceipt.payment_status!=='PAID'"><td>Sisa Piutang</td><td>{{money(selectedReceipt.grand_total-selectedReceipt.paid_amount)}}</td></tr></tfoot></table><p v-if="selectedReceipt.notes" class="receipt-notes">Catatan: {{selectedReceipt.notes}}</p><p v-if="selectedReceipt.status==='VOID'" class="receipt-void">TRANSAKSI DIBATALKAN<br>{{selectedReceipt.void_reason}}</p><footer>Terima kasih</footer></section>

      <div v-if="modal" class="modal-backdrop" @mousedown.self="modal==='item'?cancelItem():modal==='customer'?closeCustomer():closeSupplier()"><section class="modal-card" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editing[modal]?'Ubah':'Tambah'}} {{modal==='item'?'Barang':modal==='customer'?'Pelanggan':'Supplier'}}</h2><p>Lengkapi data berikut, lalu simpan perubahan.</p></div><button class="modal-close" aria-label="Tutup" @click="modal==='item'?cancelItem():modal==='customer'?closeCustomer():closeSupplier()">×</button></div>
        <form v-if="modal==='item'" class="grid" @submit.prevent="saveItem"><label>Kode / SKU<input v-model.trim="itemForm.sku" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: ATK-001" required></label><label>Nama<input v-model.trim="itemForm.name" minlength="3" maxlength="100" required></label><label>Kategori<select v-model="itemForm.category_id" required><option :value="null" disabled>Pilih kategori</option><option v-for="v in data.categories" :value="v.id">{{v.name}}</option></select></label><label>Merek<input v-model.trim="itemForm.brand_name" minlength="2" maxlength="100" placeholder="Contoh: Lenovo" required></label><label>Supplier<select v-model="itemForm.supplier_id"><option :value="null">Tanpa supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.name}}</option></select></label><div class="wide form-section"><div class="form-row"><label>Satuan kemasan<select v-model="itemForm.unit_id" required><option :value="null" disabled>Contoh: Box</option><option v-for="v in data.units" :value="v.id">{{v.name}}</option></select></label><label>Satuan dasar/eceran<select v-model="itemForm.base_unit_id" required><option :value="null" disabled>Contoh: Pcs</option><option v-for="v in data.units" :value="v.id">{{v.name}}</option></select></label><label>Isi per kemasan<input v-model.number="itemForm.units_per_package" type="number" min="1" required><small>Contoh: satu box berisi 12 pcs.</small></label></div><label class="check-label"><input v-model="itemForm.allow_retail" type="checkbox" :disabled="Number(itemForm.units_per_package)<=1"> Barang boleh dibeli dan dijual eceran</label></div><div class="wide form-row"><label>Stok awal (satuan dasar)<input v-model.number="itemForm.stock" type="number" min="0" required><small>Masukkan jumlah pcs, bukan jumlah box.</small></label><label>Harga beli/kemasan (Rp)<input :value="itemForm.cost" @input="setCurrency($event,itemForm,'cost')" type="number" min="0" step="1" inputmode="numeric" required></label><label>Harga jual/kemasan (Rp)<input :value="itemForm.price" @input="setCurrency($event,itemForm,'price')" type="number" min="0" step="1" inputmode="numeric" required></label></div><div v-if="itemForm.allow_retail&&Number(itemForm.units_per_package)>1" class="wide form-row"><label>Harga beli/eceran (Rp)<input :value="itemForm.retail_cost" @input="setCurrency($event,itemForm,'retail_cost')" type="number" min="0" step="1" inputmode="numeric" required></label><label>Harga jual/eceran (Rp)<input :value="itemForm.retail_price" @input="setCurrency($event,itemForm,'retail_price')" type="number" min="0" step="1" inputmode="numeric" required></label><div class="form-placeholder" aria-hidden="true"></div></div><label class="wide">Deskripsi<textarea v-model="itemForm.description" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="cancelItem()">Batal</button><button class="primary">{{editing.item?'Simpan Perubahan':'Simpan Barang'}}</button></div></form>
        <form v-else-if="modal==='customer'" class="grid" @submit.prevent="saveCustomer"><label>Kode Anggota<input v-model.trim="customerForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: AGT-001" required></label><label>Nama<input v-model.trim="customerForm.name" minlength="3" maxlength="120" required></label><label>Nomor Telepon<input v-model="customerForm.phone" type="tel" inputmode="numeric" minlength="8" maxlength="20" autocomplete="tel" placeholder="8–20 digit, contoh: 081234567890"></label><label class="wide">Alamat<textarea v-model="customerForm.address" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeCustomer">Batal</button><button class="primary">{{editing.customer?'Simpan Perubahan':'Simpan Pelanggan'}}</button></div></form>
        <form v-else class="grid" @submit.prevent="saveSupplier"><label>Kode Supplier<input v-model.trim="supplierForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: SUP-001" required></label><label>Nama<input v-model.trim="supplierForm.name" minlength="3" maxlength="100" required></label><label>Nomor Telepon<input v-model="supplierForm.phone" type="tel" inputmode="numeric" minlength="8" maxlength="20" autocomplete="tel" placeholder="8–20 digit, contoh: 081234567890" required></label><label class="wide">Alamat<textarea v-model="supplierForm.address" minlength="5" required/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeSupplier">Batal</button><button class="primary">{{editing.supplier?'Simpan Perubahan':'Simpan Supplier'}}</button></div></form>
      </section></div>
      <div v-if="userModal" class="modal-backdrop" @mousedown.self="closeUser"><section class="modal-card user-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editingUser?'Ubah':'Tambah'}} Pengguna</h2><p>Password saat edit boleh dikosongkan jika tidak ingin diganti.</p></div><button class="modal-close" aria-label="Tutup" @click="closeUser">×</button></div><form class="grid" @submit.prevent="saveUser"><label>Nama<input v-model.trim="userForm.name" minlength="2" maxlength="100" required></label><label>Email<input v-model.trim="userForm.email" type="email" required></label><label>Password<input v-model="userForm.password" type="password" minlength="8" :required="!editingUser" autocomplete="new-password"></label><label>Role<select v-model="userForm.role" :disabled="String(editingUser)===String(currentUser.id)"><option value="admin">Admin</option><option value="cashier">Kasir</option><option value="viewer">Viewer</option></select><small v-if="String(editingUser)===String(currentUser.id)">Role akun sendiri tidak dapat diubah.</small></label><label class="check-label"><input v-model="userForm.active" type="checkbox" :disabled="String(editingUser)===String(currentUser.id)"> Akun aktif</label><div class="modal-actions wide"><button type="button" class="soft" @click="closeUser">Batal</button><button class="primary">Simpan</button></div></form></section></div>
    </main>
    <Transition name="snackbar"><div v-if="undoSnackbar.visible" class="undo-snackbar" role="status" aria-live="polite"><span>{{undoSnackbar.message}}</span><button :disabled="undoSnackbar.busy" @click="undoSoftDelete">{{undoSnackbar.busy?'Memulihkan…':'Urungkan'}}</button><button class="undo-close" aria-label="Tutup notifikasi" @click="closeUndoSnackbar">×</button><i aria-hidden="true"></i></div></Transition>
  </div>
</template>

<style scoped>
.form-section {
  display: grid;
  gap: 6px;
}
.form-row {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
  align-items: start;
}
.form-section .check-label {
  margin-top: 0;
  padding-bottom: 0;
}
@media (max-width: 700px) {
  .form-row {
    grid-template-columns: 1fr;
  }
  .form-placeholder {
    display: none;
  }
}
</style>
