<script setup lang="ts">
import Swal from 'sweetalert2'

const route = useRoute()

const api = useKoperasiApi()
const currentUser = ref<any>(null)
const authReady = ref(false)
const loginError = ref('')
const loginForm = reactive({ email:'', password:'' })
const { formatNumber, setCurrency } = useCurrencyInput()
const { downloadExcel, downloadWorkbook, parseExcel } = useExcelData()
const allNav = [
  ['dashboard', 'Dashboard', '/'], ['items', 'Barang', '/barang'], ['customers', 'Pelanggan', '/pelanggan'], ['suppliers', 'Supplier', '/supplier'],
  ['sale', 'Kasir', '/kasir'], ['purchase', 'Pembelian', '/pembelian'], ['history', 'Histori', '/histori'], ['debts', 'Piutang', '/piutang'], ['masters', 'Pengaturan Barang', '/pengaturan'], ['users', 'Pengguna', '/pengguna'], ['audit', 'Audit Log', '/audit'],
]
const nav = computed(()=>allNav.filter(([key])=>{
  if(['users','audit'].includes(key))return currentUser.value?.role==='admin'
  return currentUser.value?.role!=='viewer'||['dashboard','items'].includes(key)
}))
const routeKey = () => allNav.find((item)=>item[2]===route.path)?.[0] || 'dashboard'
const active = ref(routeKey())
const loading = ref(false)
const submitting = ref(false)
const error = ref('')
const notice = ref('')
const data = reactive<any>({ dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[],users:[],auditLogs:[] })
const editing = reactive<any>({ item:null, customer:null, supplier:null, master:null, transaction:null })
const printMode = ref<null|'monthly'|'receipt'>(null)
const modal = ref<null|'item'|'customer'|'supplier'>(null)
const filters = reactive({ itemSearch:'', category:'', stock:'', customerSearch:'', supplierSearch:'', historySearch:'', historyType:'', historyStatus:'', auditSearch:'', auditAction:'' })
const sorting = reactive({
  items:'name:asc', customers:'name:asc', suppliers:'name:asc',
  transactions:'transaction_date:desc', users:'name:asc', daily:'date:asc', audit:'created_at:desc',
})
const money = (v:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const { dashboardYear,dashboardMonth,years,months,maxSales,monthlyReportTransactions,monthlyReportTotal,dashboardPeriods,dailyTotals,loadDashboard } = useDashboard(api,data)
const { masterForm,loadMasters,openMaster,saveMaster,editMaster,deleteMaster,findOrCreateMaster } = useMasters({api,data,editing,submit,reloadItems:()=>loadItems()})
const { itemForm,itemImport,filteredItems,loadItems,saveItem,openItem,editItem,cancelItem,removeItem } = useItems({api,data,filters,editing,modal,submit,findOrCreateMaster})
const { transactionForm,transactionContext,expandedTransaction,selectedReceipt,lineTotal,changeAmount,transactionItems,filteredTransactions,loadTransactions,voidTransaction,addLine,resetTransaction,editTransaction,saveTransaction,chooseItem,printReceipt } = useTransactions({api,data,active,editing,filters,submit,reloadDashboard:()=>loadDashboard(),reloadItems:()=>loadItems(),reloadDebts:()=>loadDebts(),money,printDocument})
const { debtPayments,loadDebts,payDebt } = useDebts({api,data,submit,reloadDashboard:()=>loadDashboard(),reloadTransactions:()=>loadTransactions()})
const { customerForm,customerImport,filteredCustomers,loadCustomers,saveCustomer,openCustomer,editCustomer,closeCustomer,removeCustomer } = useCustomers({api,data,transactionForm,filters,editing,modal,submit})
const { supplierForm,supplierImport,filteredSuppliers,loadSuppliers,saveSupplier,openSupplier,editSupplier,closeSupplier,removeSupplier } = useSuppliers({api,data,filters,editing,modal,submit})
const { userForm,userModal,editingUser,loadUsers,openUser,closeUser,saveUser,removeUser } = useUsers({api,data,currentUser,submit})
const sortedItems = useSorting<any>(filteredItems, () => sorting.items)
const sortedCustomers = useSorting<any>(filteredCustomers, () => sorting.customers)
const sortedSuppliers = useSorting<any>(filteredSuppliers, () => sorting.suppliers)
const sortableTransactions = computed(() => filteredTransactions.value.map((transaction:any) => ({
  ...transaction,
  party_name: transaction.customer_name || transaction.supplier_name || '',
})))
const sortedTransactions = useSorting<any>(sortableTransactions, () => sorting.transactions)
const sortedUsers = useSorting<any>(() => data.users, () => sorting.users)
const sortedDaily = useSorting<any>(() => data.dashboard.daily || [], () => sorting.daily)
const filteredAuditLogs = computed(() => data.auditLogs.filter((entry:any) => {
  const query = filters.auditSearch.toLowerCase()
  const matchesSearch = !query || [entry.user_name,entry.user_email,entry.entity_type,entry.path].some(value => String(value||'').toLowerCase().includes(query))
  return matchesSearch && (!filters.auditAction || entry.action === filters.auditAction)
}))
const sortedAuditLogs = useSorting<any>(filteredAuditLogs, () => sorting.audit)
const itemPage = reactive(usePagination<any>(sortedItems))
const customerPage = reactive(usePagination<any>(sortedCustomers))
const supplierPage = reactive(usePagination<any>(sortedSuppliers))
const transactionPage = reactive(usePagination<any>(sortedTransactions))
const debtPage = reactive(usePagination<any>(() => data.debts))
const userPage = reactive(usePagination<any>(sortedUsers))
const auditPage = reactive(usePagination<any>(sortedAuditLogs, 20))

const jakartaDateTime = (value:string) => new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value))

async function runLoaders(loaders:Array<()=>Promise<void>>){loading.value=true;error.value='';try{await Promise.all(loaders.map(loader=>loader()))}catch(e:any){error.value=e?.data?.message||e.message||'Gagal memuat data'}finally{loading.value=false}}
async function loadActiveRoute(){
  const loaders:Record<string,Array<()=>Promise<void>>>={
    dashboard:[loadDashboard,loadTransactions,loadDebts],items:[loadItems,loadSuppliers,loadMasters],customers:[loadCustomers],suppliers:[loadSuppliers],
    sale:[loadItems,loadCustomers,loadMasters],purchase:[loadItems,loadSuppliers,loadMasters],history:[loadTransactions],debts:[loadDebts],masters:[loadMasters],users:[loadUsers],audit:[async()=>{data.auditLogs=await api.auditLogs()}],
  }
  await runLoaders(loaders[active.value]||loaders.dashboard)
}
async function submit(action:()=>Promise<any>, message:string, reload:Array<()=>Promise<void>>, confirmation:string|false=false){if(submitting.value)return false;if(confirmation!==false){const result=await Swal.fire({icon:'question',title:'Konfirmasi',text:confirmation,showCancelButton:true,confirmButtonText:'Ya, simpan',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!result.isConfirmed)return false}error.value='';notice.value='';submitting.value=true;try{await action();await runLoaders(reload);await Swal.fire({icon:'success',title:'Berhasil',text:message,confirmButtonColor:'#1d6b43'});return true}catch(e:any){const message=e?.data?.message||e.message||'Gagal menyimpan data';await Swal.fire({icon:'error',title:'Gagal',text:message,confirmButtonColor:'#1d6b43'});return false}finally{submitting.value=false}}
watch(()=>route.path,async()=>{const next=routeKey();if(next===active.value)return;active.value=next;if(currentUser.value)await loadActiveRoute()})
watch(active,(next)=>{error.value='';notice.value='';modal.value=null;if((next==='sale'||next==='purchase')&&transactionContext.value!==next){resetTransaction(next);transactionContext.value=next}})
watch(dashboardYear,()=>runLoaders([loadDashboard]))
watch(dashboardMonth,()=>runLoaders([loadDashboard]))
function blockInvalidNumber(event:KeyboardEvent){const target=event.target as HTMLInputElement;if(target?.type==='number'&&['e','E','+','-','.'].includes(event.key))event.preventDefault()}
function sanitizeNumeric(event:Event){const target=event.target as HTMLInputElement;if(target?.type==='tel')target.value=target.value.replace(/\D/g,'')}
async function exportData(kind:'items'|'customers'|'suppliers'|'transactions'){
  const date=new Date().toISOString().slice(0,10)
  if(kind==='items')await downloadExcel(`barang-${date}.xlsx`,['sku','name','description','supplier_code','category','brand','unit','stock','cost','price'],data.items.map((v:any)=>[v.sku,v.name,v.description,data.suppliers.find((s:any)=>s.id===v.supplier_id)?.code||'',v.category_name||'',v.brand_name||'',v.unit_name||'',v.stock,v.cost,v.price]))
  if(kind==='customers')await downloadExcel(`pelanggan-${date}.xlsx`,['code','name','phone','address'],data.customers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='suppliers')await downloadExcel(`supplier-${date}.xlsx`,['code','name','phone','address'],data.suppliers.map((v:any)=>[v.code,v.name,v.phone,v.address]))
  if(kind==='transactions')await downloadExcel(`histori-transaksi-${date}.xlsx`,['invoice','date','type','party','status','payment_status','total','received','change','items','notes'],filteredTransactions.value.map((v:any)=>[v.invoice_no,v.transaction_date,v.transaction_type,v.customer_name||v.supplier_name||'',v.status,v.payment_status,v.grand_total,v.amount_received,v.change_amount,v.items.map((x:any)=>`${x.item_name} (${x.quantity} x ${x.unit_price})`).join('; '),v.notes]))
}
async function login(){loginError.value='';submitting.value=true;try{const result=await api.login(loginForm.email,loginForm.password);api.token.value=result.access_token;currentUser.value=result.user;loginForm.password='';active.value='dashboard';await runLoaders([loadDashboard,loadTransactions,loadDebts]);await navigateTo('/')}catch(e:any){loginError.value=e?.data?.message||'Login gagal'}finally{submitting.value=false}}
async function logout(){try{await api.logout()}finally{api.token.value=null;currentUser.value=null;Object.assign(data,{dashboard:{},items:[],customers:[],suppliers:[],categories:[],brands:[],units:[],payment_methods:[],transactions:[],debts:[]});await navigateTo('/login')}}
function sameText(a:any,b:any){return String(a??'').trim()===String(b??'').trim()}
function sameCode(a:any,b:any){return String(a??'').trim().toLowerCase()===String(b??'').trim().toLowerCase()}
async function importData(kind:'items'|'customers'|'suppliers',event:Event){
  const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return
  try{
    const rows=await parseExcel(file);if(!rows.length)throw new Error('Excel kosong atau formatnya tidak sesuai template export.')
    const confirm=await Swal.fire({icon:'question',title:`Import ${rows.length} baris?`,text:'Data dengan kode yang sama akan diperbarui.',showCancelButton:true,confirmButtonText:'Ya, import',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!confirm.isConfirmed)return
    submitting.value=true
    let created=0,updated=0,skipped=0
    const knownCustomers=[...data.customers],knownSuppliers=[...data.suppliers],knownItems=[...data.items]
    for(let index=0;index<rows.length;index++){
      const row:any=rows[index]
      try{
        if(kind==='customers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi');if(String(row.code).toUpperCase()==='UMUM'){skipped++;continue}
          const existing=knownCustomers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateCustomer(existing.id,body):api.createCustomer(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownCustomers.push({...body,id:null})
        }else if(kind==='suppliers'){
          if(!row.code||!row.name)throw new Error('code dan name wajib diisi')
          const existing=knownSuppliers.find((v:any)=>sameCode(v.code,row.code));const body={code:row.code,name:row.name,phone:row.phone||'',address:row.address||''}
          if(existing&&sameCode(existing.code,body.code)&&sameText(existing.name,body.name)&&sameText(existing.phone,body.phone)&&sameText(existing.address,body.address)){skipped++;continue}
          if(existing&&!existing.id)throw new Error(`code ${row.code} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateSupplier(existing.id,body):api.createSupplier(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownSuppliers.push({...body,id:null})
        }else{
          if(!row.sku||!row.name)throw new Error('sku dan name wajib diisi')
          const supplier=row.supplier_code?data.suppliers.find((v:any)=>v.code.toLowerCase()===row.supplier_code.toLowerCase()):null;if(row.supplier_code&&!supplier)throw new Error(`supplier ${row.supplier_code} tidak ditemukan`)
          const body={sku:row.sku,name:row.name,description:row.description||'',supplier_id:supplier?.id||null,category_id:await findOrCreateMaster('categories',data.categories,row.category),brand_id:await findOrCreateMaster('brands',data.brands,row.brand),unit_id:await findOrCreateMaster('units',data.units,row.unit),stock:Number(row.stock||0),cost:Number(row.cost||0),price:Number(row.price||0)}
          const identical=knownItems.find((v:any)=>sameText(v.name,body.name)&&Number(v.supplier_id||0)===Number(body.supplier_id||0)&&Number(v.unit_id||0)===Number(body.unit_id||0)&&Number(v.price||0)===Number(body.price||0))
          if(identical){skipped++;continue}
          const existing=knownItems.find((v:any)=>sameCode(v.sku,row.sku));if(existing&&!existing.id)throw new Error(`sku ${row.sku} muncul lebih dari sekali dengan data berbeda`)
          await (existing?api.updateItem(existing.id,body):api.createItem(body));existing?updated++:created++;if(existing)Object.assign(existing,body);else knownItems.push({...body,id:null})
        }
      }catch(e:any){throw new Error(`Baris ${index+2}: ${e?.data?.message||e.message}`)}
    }
    await runLoaders(kind==='items'?[loadItems,loadMasters]:kind==='customers'?[loadCustomers]:[loadSuppliers]);await Swal.fire({icon:'success',title:'Import selesai',text:`${created} dibuat, ${updated} diperbarui, ${skipped} dilewati.`,confirmButtonColor:'#1d6b43'})
  }catch(e:any){await Swal.fire({icon:'error',title:'Import gagal',text:e.message||'File tidak dapat diproses.',confirmButtonColor:'#1d6b43'})}finally{submitting.value=false;input.value=''}
}
async function printDocument(mode:'monthly'|'receipt'){printMode.value=mode;await nextTick();window.print();printMode.value=null}
function printMonthlyReport(){printDocument('monthly')}
async function exportMonthlyReport(){
  const prompt=await Swal.fire({title:'Export laporan bulanan',input:'textarea',inputLabel:'Catatan (opsional)',inputPlaceholder:'Tambahkan catatan untuk sheet laporan…',showCancelButton:true,confirmButtonText:'Export Excel',cancelButtonText:'Batal',confirmButtonColor:'#1d6b43'});if(!prompt.isConfirmed)return
  const transactionRows=(values:any[])=>values.map(v=>[v.invoice_no,jakartaDateTime(v.transaction_date),v.customer_name||v.supplier_name||'',v.payment_method_name||'',v.payment_status,v.status,v.grand_total,v.paid_amount,v.notes||'',v.items.map((x:any)=>`${x.item_name} (${x.quantity} x ${x.unit_price})`).join('; ')])
  const sheets:any[]=[
    {name:'Ringkasan Bulanan',columns:['Metrik','Nilai'],rows:[['Periode',`${months[dashboardMonth.value-1]} ${dashboardYear.value}`],['Total pemasukan',dailyTotals.value.income],['Total pengeluaran',dailyTotals.value.expense],['Piutang dibuat',dailyTotals.value.debt],['Pendapatan bersih',dailyTotals.value.net_income],['Jumlah transaksi penjualan',monthlyReportTransactions.value.length]]},
    {name:'Penjualan Harian',columns:['Tanggal','Pemasukan','Pengeluaran','Piutang','Pendapatan Bersih'],rows:(data.dashboard.daily||[]).map((v:any)=>[v.date,v.income,v.expense,v.debt,v.net_income]).concat([['TOTAL',dailyTotals.value.income,dailyTotals.value.expense,dailyTotals.value.debt,dailyTotals.value.net_income]])},
    {name:'Riwayat Penjualan',columns:['Invoice','Tanggal WIB','Pelanggan','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='SALE'))},
    {name:'Riwayat Pembelian',columns:['Invoice','Tanggal WIB','Supplier','Metode','Pembayaran','Status','Total','Dibayar','Catatan','Item'],rows:transactionRows(data.transactions.filter((v:any)=>v.transaction_type==='PURCHASE'))},
    {name:'Piutang',columns:['Invoice','Pelanggan','Nilai Awal','Sisa','Status','Tanggal WIB'],rows:data.debts.map((v:any)=>[v.invoice_no,v.customer_name,v.original_amount,v.remaining_amount,v.status,jakartaDateTime(v.created_at)])},
  ];if(String(prompt.value||'').trim())sheets.push({name:'Catatan',columns:['Catatan','Dibuat pada'],rows:[[String(prompt.value).trim(),jakartaDateTime(new Date().toISOString())]]})
  await downloadWorkbook(`laporan-${dashboardYear.value}-${String(dashboardMonth.value).padStart(2,'0')}.xlsx`,sheets)
}
onMounted(async()=>{try{if(api.token.value){currentUser.value=await api.me();if(route.path==='/login'){active.value='dashboard';await runLoaders([loadDashboard,loadTransactions,loadDebts]);await navigateTo('/')}else await loadActiveRoute()}else if(route.path!=='/login')await navigateTo('/login')}catch{api.token.value=null;currentUser.value=null;if(route.path!=='/login')await navigateTo('/login')}finally{authReady.value=true}})
</script>

<template>
  <section v-if="authReady&&!currentUser" class="login-page"><form class="login-card" @submit.prevent="login"><div class="login-mark">K</div><h1>Masuk ke Koperasi</h1><p>Gunakan akun yang diberikan administrator.</p><label>Email<input v-model.trim="loginForm.email" type="email" autocomplete="username" required></label><label>Password<input v-model="loginForm.password" type="password" autocomplete="current-password" required></label><p v-if="loginError" class="alert error">{{loginError}}</p><button class="primary" :disabled="submitting">{{submitting?'Memproses…':'Masuk'}}</button></form></section>
  <div v-else-if="currentUser" class="app-shell">
    <aside><div class="brand"><span>K</span><div><strong>Koperasi</strong><small>Operational Console</small></div></div><nav><NuxtLink v-for="n in nav" :key="n[0]" :to="n[2]" :class="{active:active===n[0]}">{{ n[1] }}</NuxtLink></nav></aside>
    <main @keydown="blockInvalidNumber" @input="sanitizeNumeric">
      <header><div><p class="eyebrow">SIG KOPERASI · GO + NUXT</p><h1>{{ nav.find(n=>n[0]===active)?.[1] }}</h1></div><div class="user-actions"><span><b>{{currentUser.name}}</b><small>{{currentUser.role}}</small></span><button class="soft" @click="logout">Keluar</button></div></header>
      <p v-if="error" class="alert error">{{ error }}</p><p v-if="notice" class="alert success">{{ notice }}</p>

      <section v-if="active==='audit'" class="panel"><div class="page-heading"><div><h2>Audit Log</h2><p>Riwayat perubahan data dan aksi pengguna. Isi request sensitif tidak disimpan.</p></div><div class="heading-actions"><PageSizeSelect v-model="auditPage.pageSize" @update:model-value="auditPage.setPage(1)"/><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button></div></div><div class="history-filters audit-filters"><input v-model="filters.auditSearch" type="search" placeholder="Cari pengguna, modul, atau path..."><select v-model="filters.auditAction"><option value="">Semua aksi</option><option value="CREATE">Tambah</option><option value="UPDATE">Ubah</option><option value="DELETE">Hapus</option><option value="VOID">Batalkan transaksi</option><option value="PAYMENT">Pembayaran</option></select><button class="soft" @click="Object.assign(filters,{auditSearch:'',auditAction:''})">Reset</button></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.audit" field="created_at" default-direction="desc">Waktu</SortableTh><SortableTh v-model="sorting.audit" field="user_name">Pengguna</SortableTh><SortableTh v-model="sorting.audit" field="action">Aksi</SortableTh><SortableTh v-model="sorting.audit" field="entity_type">Modul / ID</SortableTh><SortableTh v-model="sorting.audit" field="status_code" class="table-center">Hasil</SortableTh><th>Alamat IP</th></tr></thead><tbody><tr v-for="entry in auditPage.pageItems" :key="entry.id"><td>{{jakartaDateTime(entry.created_at)}}</td><td><strong>{{entry.user_name}}</strong><small>{{entry.user_email}}</small></td><td><span class="role-badge">{{entry.action}}</span><small>{{entry.method}} {{entry.path}}</small></td><td>{{entry.entity_type}}<small v-if="entry.entity_id">ID {{entry.entity_id}}</small></td><td class="table-center" :class="entry.status_code<400?'income':'expense'">{{entry.status_code<400?'Berhasil':'Ditolak'}} · {{entry.status_code}}</td><td>{{entry.ip_address||'—'}}</td></tr><tr v-if="!auditPage.totalItems"><td colspan="6" class="empty">Belum ada aktivitas yang cocok.</td></tr></tbody></table></div><PaginationControls v-bind="auditPage" @update:page="auditPage.setPage"/></section>
      <section v-else-if="active==='users'" class="panel"><div class="page-heading"><div><h2>Daftar Pengguna</h2><p>Kelola akun dan hak akses aplikasi.</p></div><div class="heading-actions"><PageSizeSelect v-model="userPage.pageSize" @update:model-value="userPage.setPage(1)"/><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="openUser()">+ Tambah Pengguna</button></div></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.users" field="name">Nama</SortableTh><SortableTh v-model="sorting.users" field="email">Email</SortableTh><SortableTh v-model="sorting.users" field="role" class="table-center">Role</SortableTh><SortableTh v-model="sorting.users" field="active" default-direction="desc" class="table-center">Status</SortableTh><th class="table-center">Aksi</th></tr></thead><tbody><tr v-for="user in userPage.pageItems" :key="user.id"><td><b>{{user.name}}</b><small v-if="String(user.id)===String(currentUser.id)"> · akun Anda</small></td><td>{{user.email}}</td><td class="table-center"><span class="role-badge">{{user.role}}</span></td><td class="table-center">{{user.active?'Aktif':'Nonaktif'}}</td><td class="table-actions"><button class="soft" @click="openUser(user)">Ubah</button><button class="danger" :disabled="String(user.id)===String(currentUser.id)" @click="removeUser(user)">Hapus</button></td></tr></tbody></table></div><PaginationControls v-bind="userPage" @update:page="userPage.setPage"/></section>
      <template v-else-if="active==='dashboard'">
        <section class="panel dashboard-toolbar"><div><strong>Periode Laporan</strong><small>Ringkasan bulan dan tahun mengikuti pilihan ini.</small></div><select v-model.number="dashboardMonth"><option v-for="(month,i) in months" :value="i+1">{{month}}</option></select><select v-model.number="dashboardYear"><option v-for="year in years" :value="year">{{year}}</option></select><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="exportMonthlyReport">Export Laporan Excel</button></section>
        <section class="period-stats"><article v-for="period in dashboardPeriods"><div><small>{{period.label}}</small><b>Pemasukan</b><strong class="income">{{money(period.value.income)}}</strong></div><div><b>Pengeluaran</b><strong class="expense">{{money(period.value.expense)}}</strong></div><div><b>Piutang Dibuat</b><strong>{{money(period.value.debt)}}</strong></div></article></section>
        <section class="operational-stats"><span>Piutang terbuka <b>{{money(data.dashboard.open_debt)}}</b></span><span>Stok menipis <b>{{data.dashboard.low_stock_items||0}} barang</b></span><span>Total barang <b>{{data.dashboard.total_items||0}}</b></span><span>Pelanggan <b>{{data.dashboard.total_customers||0}}</b></span></section>
        <section class="panel chart-panel"><div class="section-title"><div><h2>Grafik Penjualan {{dashboardYear}}</h2><small>Total nilai transaksi penjualan per bulan</small></div></div><div class="chart"><div v-for="(value,i) in data.dashboard.monthly_sales||[]" :key="Number(i)" class="bar-column"><strong>{{value?money(value):'Rp0'}}</strong><div class="bar-track"><span :style="{height:`${Math.max((value/maxSales)*100,value?4:0)}%`}"></span></div><small>{{months[Number(i)]}}</small></div></div></section>
        <section class="panel daily-report"><div class="section-title"><div><h2>Rekap Harian {{months[dashboardMonth-1]}} {{dashboardYear}}</h2><small>Perhitungan tanggal menggunakan zona waktu Asia/Jakarta (UTC+7).</small></div></div><div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.daily" field="date">Tanggal</SortableTh><SortableTh v-model="sorting.daily" field="income" default-direction="desc">Total Pemasukan</SortableTh><SortableTh v-model="sorting.daily" field="expense" default-direction="desc">Total Pengeluaran</SortableTh><SortableTh v-model="sorting.daily" field="debt" default-direction="desc">Total Piutang</SortableTh><SortableTh v-model="sorting.daily" field="net_income" default-direction="desc">Total Pendapatan</SortableTh></tr></thead><tbody><tr v-for="row in sortedDaily" :key="row.date"><td>{{new Date(`${row.date}T00:00:00+07:00`).toLocaleDateString(`id-ID`,{weekday:`long`,day:`2-digit`,month:`short`,timeZone:`Asia/Jakarta`})}}</td><td>{{money(row.income)}}</td><td>{{money(row.expense)}}</td><td>{{money(row.debt)}}</td><td :class="row.net_income<0?`expense`:`income`">{{money(row.net_income)}}</td></tr></tbody><tfoot><tr><th>TOTAL</th><th>{{money(dailyTotals.income)}}</th><th>{{money(dailyTotals.expense)}}</th><th>{{money(dailyTotals.debt)}}</th><th>{{money(dailyTotals.net_income)}}</th></tr></tfoot></table></div></section>
        <section class="print-report" :class="{'print-target':printMode==='monthly'}"><h1>Laporan Penjualan Bulanan</h1><p>Periode: {{months[dashboardMonth-1]}} {{dashboardYear}}</p><table><thead><tr><th>Tanggal</th><th>Invoice</th><th>Pelanggan</th><th>Total</th></tr></thead><tbody><tr v-for="v in monthlyReportTransactions"><td>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</td><td>{{v.invoice_no}}</td><td>{{v.customer_name||'Umum'}}</td><td>{{money(v.grand_total)}}</td></tr><tr v-if="!monthlyReportTransactions.length"><td colspan="4">Tidak ada transaksi penjualan.</td></tr></tbody><tfoot><tr><th colspan="3">Total Penjualan</th><th>{{money(monthlyReportTotal)}}</th></tr></tfoot></table></section>
      </template>

      <template v-else-if="active==='items'">
        <div class="page-heading"><div><h2>Daftar Barang</h2><p>Kelola katalog dan persediaan barang.</p></div><div class="heading-actions"><input ref="itemImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('items',$event)"><button class="soft" @click="itemImport?.click()">Import Excel</button><button class="soft" @click="exportData('items')">Export Excel</button><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="openItem()">+ Tambah Barang</button></div></div>
        <section class="panel toolbar"><PageSizeSelect v-model="itemPage.pageSize" @update:model-value="itemPage.setPage(1)"/><input v-model="filters.itemSearch" type="search" placeholder="Cari nama atau SKU..."><select v-model="filters.category"><option value="">Semua kategori</option><option v-for="v in data.categories" :value="String(v.id)">{{v.name}}</option></select><select v-model="filters.stock"><option value="">Semua stok</option><option value="empty">Stok habis</option><option value="low">Stok menipis (1-5)</option><option value="ready">Stok tersedia</option></select><button class="soft" @click="Object.assign(filters,{itemSearch:'',category:'',stock:''})">Reset Filter</button></section>
        <DataTable v-model:sorting="sorting.items" actions :rows="itemPage.pageItems" :columns="[['sku','Kode / SKU'],['name','Barang'],['category_name','Kategori'],['unit_name','Satuan'],['stock','Stok', null, 'table-center','desc'],['cost','Harga Beli','money','table-center','desc'],['price','Harga Jual','money','table-center','desc']]" @edit="editItem" @delete="removeItem" />
        <PaginationControls v-bind="itemPage" @update:page="itemPage.setPage"/>
      </template>

      <template v-else-if="active==='customers' || active==='suppliers'">
        <div class="page-heading"><div><h2>Daftar {{active==='customers'?'Pelanggan':'Supplier'}}</h2><p>Kelola data {{active==='customers'?'pelanggan dan anggota':'mitra pemasok'}}.</p></div><div class="heading-actions"><input v-if="active==='customers'" ref="customerImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('customers',$event)"><input v-else ref="supplierImport" class="file-input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="importData('suppliers',$event)"><button class="soft" @click="active==='customers'?customerImport?.click():supplierImport?.click()">Import Excel</button><button class="soft" @click="exportData(active==='customers'?'customers':'suppliers')">Export Excel</button><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary" @click="active==='customers'?openCustomer():openSupplier()">+ Tambah {{active==='customers'?'Pelanggan':'Supplier'}}</button></div></div>
        <section class="panel toolbar party-toolbar"><PageSizeSelect v-if="active==='customers'" v-model="customerPage.pageSize" @update:model-value="customerPage.setPage(1)"/><PageSizeSelect v-else v-model="supplierPage.pageSize" @update:model-value="supplierPage.setPage(1)"/><input v-if="active==='customers'" v-model="filters.customerSearch" type="search" placeholder="Cari kode, nama, atau telepon..."><input v-else v-model="filters.supplierSearch" type="search" placeholder="Cari nama, telepon, atau alamat..."></section>
        <template v-if="active==='customers'"><DataTable v-model:sorting="sorting.customers" actions :rows="customerPage.pageItems" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon',null,'table-center'],['address','Alamat']]" @edit="editCustomer" @delete="removeCustomer"/><PaginationControls v-bind="customerPage" @update:page="customerPage.setPage"/></template><template v-else><DataTable v-model:sorting="sorting.suppliers" actions :rows="supplierPage.pageItems" :columns="[['code','Kode'],['name','Nama'],['phone','Telepon',null,'table-center'],['address','Alamat']]" @edit="editSupplier" @delete="removeSupplier"/><PaginationControls v-bind="supplierPage" @update:page="supplierPage.setPage"/></template>
      </template>

      <template v-else-if="active==='sale'||active==='purchase'">
        <form class="panel transaction" @submit.prevent="saveTransaction(active==='sale'?'SALE':'PURCHASE')">
          <div class="section-title"><div><h2>{{editing.transaction?'Edit ':''}}{{active==='sale'?'Transaksi Kasir':'Penerimaan Pembelian'}}</h2><p class="hint">{{editing.transaction?'Perubahan barang otomatis menyesuaikan stok.':active==='sale'?'Gunakan pelanggan UMUM untuk non-anggota. Kurang bayar hanya dapat dicatat dengan metode Piutang.':'Pilih supplier lebih dulu; hanya barang dari supplier tersebut yang dapat ditambahkan.'}}</p></div><div class="heading-actions"><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh Data'}}</button><button v-if="editing.transaction" type="button" class="soft" @click="resetTransaction()">Batal Edit</button></div></div>
          <div class="transaction-layout"><div class="transaction-products">
            <label v-if="active==='sale'">Pelanggan<select v-model="transactionForm.customer_id" required><option v-for="v in data.customers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label><label v-else>Supplier<select v-model="transactionForm.supplier_id" required><option :value="null" disabled>Pilih supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.code}} · {{v.name}}</option></select></label>
            <div class="line-head"><span>Barang</span><span>Jumlah</span><span>Harga Satuan</span><span>Subtotal</span><span></span></div><div class="lines"><div v-for="(line,i) in transactionForm.items" :key="i" class="line"><select v-model="line.item_id" required :disabled="active==='purchase'&&!transactionForm.supplier_id" @change="chooseItem(line)"><option :value="null" disabled>{{active==='purchase'&&!transactionForm.supplier_id?'Pilih supplier dahulu':'Pilih barang'}}</option><option v-for="v in transactionItems" :value="v.id">{{v.sku}} · {{v.name}} (stok {{v.stock}})</option></select><input v-model.number="line.quantity" aria-label="Jumlah barang" type="number" min="1" placeholder="Jumlah" required><input :value="formatNumber(line.unit_price)" @input="setCurrency($event,line,'unit_price')" aria-label="Harga satuan" inputmode="numeric" placeholder="0" required><strong>{{money(line.quantity*line.unit_price)}}</strong><button type="button" class="icon" :disabled="transactionForm.items.length===1" @click="transactionForm.items.splice(i,1)">×</button></div></div>
            <p v-if="active==='purchase'&&transactionForm.supplier_id&&!transactionItems.length" class="empty supplier-empty">Belum ada barang yang terhubung ke supplier ini. Atur supplier pada master Barang dahulu.</p><button type="button" class="soft add-item" :disabled="active==='purchase'&&!transactionForm.supplier_id" @click="addLine">+ Tambah Barang</button><label class="transaction-notes">Catatan<textarea v-model="transactionForm.notes" placeholder="Opsional: catatan transaksi"/></label>
          </div><aside class="checkout-stack"><div class="checkout-label">Ringkasan Transaksi</div><div class="checkout-row grand-total"><span>Grand Total</span><strong>{{money(lineTotal)}}</strong></div><label>Metode Pembayaran<select v-model="transactionForm.payment_method_id" required><option :value="null" disabled>Pilih metode pembayaran</option><option v-for="v in data.payment_methods" :value="v.id">{{v.name}}</option></select></label><label>Pembayaran (Rp)<input :value="formatNumber(transactionForm.paid_amount)" @input="setCurrency($event,transactionForm,'paid_amount')" inputmode="numeric" placeholder="0" required></label><div class="checkout-row" :class="changeAmount<0?'shortage':'change'"><span>{{changeAmount<0?'Kurang Bayar':'Kembalian'}}</span><strong>{{money(Math.abs(changeAmount))}}</strong></div><button type="submit" class="primary" :disabled="!lineTotal||submitting">{{submitting?'Menyimpan…':editing.transaction?'Simpan Perubahan':'Simpan Transaksi'}}</button></aside></div>
        </form>
      </template>

      <section v-else-if="active==='history'" class="panel history">
        <div class="history-note"><strong>Aturan stok transaksi</strong><span>Batalkan penjualan: stok barang kembali. Batalkan pembelian: stok dikurangi dan akan ditolak jika barang sudah terpakai. Transaksi dengan cicilan piutang tidak dapat diedit atau dibatalkan.</span></div>
        <div class="history-filters"><PageSizeSelect v-model="transactionPage.pageSize" @update:model-value="transactionPage.setPage(1)"/><input v-model="filters.historySearch" type="search" placeholder="Cari invoice, pelanggan, supplier, atau catatan..."><select v-model="filters.historyType"><option value="">Semua tipe</option><option value="SALE">Penjualan</option><option value="PURCHASE">Pembelian</option></select><select v-model="filters.historyStatus"><option value="">Semua status</option><option value="ACTIVE">Aktif</option><option value="VOID">Dibatalkan</option><option value="PAID">Lunas</option><option value="PARTIAL">Sebagian</option><option value="UNPAID">Belum bayar</option></select><button type="button" class="soft" @click="Object.assign(filters,{historySearch:'',historyType:'',historyStatus:''})">Reset</button><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button type="button" class="soft" @click="exportData('transactions')">Export Histori</button></div>
        <div class="table-wrap"><table><thead><tr><SortableTh v-model="sorting.transactions" field="transaction_date" default-direction="desc">Invoice / Tanggal</SortableTh><SortableTh v-model="sorting.transactions" field="transaction_type" class="table-center">Tipe</SortableTh><SortableTh v-model="sorting.transactions" field="party_name">Pelanggan / Supplier</SortableTh><SortableTh v-model="sorting.transactions" field="payment_status" class="table-center">Status</SortableTh><SortableTh v-model="sorting.transactions" field="grand_total" default-direction="desc" class="table-center">Total</SortableTh><th class="table-center">Aksi</th></tr></thead><tbody><template v-for="v in transactionPage.pageItems" :key="v.id"><tr :class="{voided:v.status==='VOID'}"><td><strong>{{v.invoice_no}}</strong><small>{{new Date(v.transaction_date).toLocaleString('id-ID')}}</small></td><td class="table-center">{{v.transaction_type==='SALE'?'Penjualan':'Pembelian'}}</td><td>{{v.customer_name||v.supplier_name||'—'}}</td><td class="table-center">{{v.status==='VOID'?'Dibatalkan':v.payment_status}}</td><td class="table-center">{{money(v.grand_total)}}</td><td class="table-actions"><button class="soft" @click="expandedTransaction=expandedTransaction===v.id?null:v.id">{{expandedTransaction===v.id?'Tutup':'Detail'}}</button><button class="soft" @click="printReceipt(v)">Struk PDF</button><button class="soft" :disabled="v.status==='VOID'" @click="editTransaction(v)">Ubah</button><button class="danger" :disabled="v.status==='VOID'" @click="voidTransaction(v)">Batalkan</button></td></tr><tr v-if="expandedTransaction===v.id" class="history-detail"><td colspan="6"><div><span v-for="line in v.items" :key="line.item_id"><b>{{line.item_name}}</b> · {{line.quantity}} × {{money(line.unit_price)}} = {{money(line.subtotal)}}</span></div><div><span>Uang diterima <b>{{money(v.amount_received)}}</b></span><span>Kembalian <b>{{money(v.change_amount)}}</b></span><span v-if="v.notes">Catatan: {{v.notes}}</span><span v-if="v.status==='VOID'">Alasan batal: {{v.void_reason}}</span></div></td></tr></template><tr v-if="!transactionPage.totalItems"><td colspan="6" class="empty">Tidak ada transaksi yang cocok</td></tr></tbody></table></div>
        <PaginationControls v-bind="transactionPage" @update:page="transactionPage.setPage"/>
      </section>
      <section v-else-if="active==='debts'" class="panel"><h2>Pembayaran Piutang Pelanggan</h2><p class="hint">Piutang dibuat otomatis ketika jumlah yang dibayar di kasir lebih kecil dari grand total. Masukkan nominal cicilan pada transaksi yang sesuai; sisa piutang akan berkurang otomatis.</p><div class="list-toolbar"><PageSizeSelect v-model="debtPage.pageSize" @update:model-value="debtPage.setPage(1)"/><button class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button></div><div class="debt" v-for="v in debtPage.pageItems" :key="v.id"><div><strong>{{v.customer_name}}</strong><small>Invoice {{v.invoice_no}}</small><small>Awal {{money(v.original_amount)}} · Sisa <b>{{money(v.remaining_amount)}}</b></small></div><form v-if="v.status==='OPEN'" @submit.prevent="payDebt(v)"><label>Nominal Pembayaran (Rp)<input :value="formatNumber(debtPayments[v.id])" @input="setCurrency($event,debtPayments,String(v.id))" inputmode="numeric" pattern="[0-9.]+" placeholder="0" required></label><button class="primary" :disabled="!debtPayments[v.id]||debtPayments[v.id]>v.remaining_amount">Catat Pembayaran</button></form><span v-else class="paid">Lunas</span></div><p v-if="!debtPage.totalItems" class="empty">Belum ada piutang pelanggan.</p><PaginationControls v-bind="debtPage" @update:page="debtPage.setPage"/></section>
      <section v-else-if="active==='masters'" class="panel"><h2>Master Data Barang</h2><p class="hint">Kelola pilihan yang muncul pada form barang dan transaksi: kategori untuk mengelompokkan barang, merek untuk produsennya, satuan untuk bentuk stok, dan metode pembayaran untuk kasir.</p><form class="inline" @submit.prevent="saveMaster"><select v-model="masterForm.table" @change="editing.master=null;masterForm.name=''"><option value="categories">Kategori</option><option value="brands">Merek</option><option value="units">Satuan</option><option value="payment_methods">Metode Pembayaran</option></select><input v-model.trim="masterForm.name" minlength="2" maxlength="100" placeholder="Masukkan nama" required><button type="button" class="soft" @click="loadActiveRoute">{{loading?'Memuat…':'Refresh'}}</button><button class="primary">{{editing.master?'Simpan':'Tambah'}}</button></form><div class="master-grid"><article v-for="table in ['categories','brands','units','payment_methods']"><h3>{{({categories:'Kategori',brands:'Merek',units:'Satuan',payment_methods:'Metode Pembayaran'} as any)[table]}}</h3><div class="master-row" v-for="v in data[table]"><span>{{v.name}}</span><button class="mini" @click="editMaster(table,v)">Ubah</button><button class="mini danger" @click="deleteMaster(table,v)">Hapus</button></div></article></div></section>

      <section v-if="selectedReceipt" class="print-receipt" :class="{'print-target':printMode==='receipt'}"><header><h1>KOPERASI</h1><p>{{selectedReceipt.transaction_type==='SALE'?'STRUK PENJUALAN':'BUKTI PEMBELIAN'}}</p></header><div class="receipt-meta"><span>Invoice</span><b>{{selectedReceipt.invoice_no}}</b><span>Tanggal</span><b>{{new Date(selectedReceipt.transaction_date).toLocaleString('id-ID')}}</b><span>{{selectedReceipt.transaction_type==='SALE'?'Pelanggan':'Supplier'}}</span><b>{{selectedReceipt.customer_name||selectedReceipt.supplier_name||'Umum'}}</b><span>Metode</span><b>{{selectedReceipt.payment_method_name||'-'}}</b></div><table><tbody><template v-for="line in selectedReceipt.items" :key="line.item_id"><tr><td colspan="2"><b>{{line.item_name}}</b></td></tr><tr><td>{{line.quantity}} × {{money(line.unit_price)}}</td><td>{{money(line.subtotal)}}</td></tr></template></tbody><tfoot><tr><th>Grand Total</th><th>{{money(selectedReceipt.grand_total)}}</th></tr><tr><td>{{selectedReceipt.transaction_type==='SALE'?'Uang Diterima':'Pembayaran'}}</td><td>{{money(selectedReceipt.amount_received)}}</td></tr><tr v-if="selectedReceipt.change_amount"><td>Kembalian</td><td>{{money(selectedReceipt.change_amount)}}</td></tr><tr v-if="selectedReceipt.payment_status!=='PAID'"><td>Sisa Piutang</td><td>{{money(selectedReceipt.grand_total-selectedReceipt.paid_amount)}}</td></tr></tfoot></table><p v-if="selectedReceipt.notes" class="receipt-notes">Catatan: {{selectedReceipt.notes}}</p><p v-if="selectedReceipt.status==='VOID'" class="receipt-void">TRANSAKSI DIBATALKAN<br>{{selectedReceipt.void_reason}}</p><footer>Terima kasih</footer></section>

      <div v-if="modal" class="modal-backdrop" @mousedown.self="modal==='item'?cancelItem():modal==='customer'?closeCustomer():closeSupplier()"><section class="modal-card" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editing[modal]?'Ubah':'Tambah'}} {{modal==='item'?'Barang':modal==='customer'?'Pelanggan':'Supplier'}}</h2><p>Lengkapi data berikut, lalu simpan perubahan.</p></div><button class="modal-close" aria-label="Tutup" @click="modal==='item'?cancelItem():modal==='customer'?closeCustomer():closeSupplier()">×</button></div>
        <form v-if="modal==='item'" class="grid" @submit.prevent="saveItem"><label>Kode / SKU<input v-model.trim="itemForm.sku" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: ATK-001" required></label><label>Nama<input v-model.trim="itemForm.name" minlength="3" maxlength="100" required></label><label>Kategori<select v-model="itemForm.category_id" required><option :value="null" disabled>Pilih kategori</option><option v-for="v in data.categories" :value="v.id">{{v.name}}</option></select></label><label>Merek<input v-model.trim="itemForm.brand_name" minlength="2" maxlength="100" placeholder="Contoh: Lenovo" required></label><label>Satuan<select v-model="itemForm.unit_id" required><option :value="null" disabled>Pilih satuan</option><option v-for="v in data.units" :value="v.id">{{v.name}}</option></select></label><label>Supplier<select v-model="itemForm.supplier_id"><option :value="null">Tanpa supplier</option><option v-for="v in data.suppliers" :value="v.id">{{v.name}}</option></select></label><label>Stok awal<input v-model.number="itemForm.stock" type="number" min="0" required></label><label>Harga beli (Rp)<input :value="itemForm.cost" @input="setCurrency($event,itemForm,'cost')" type="number" min="0" step="1" inputmode="numeric" required></label><label>Harga jual (Rp)<input :value="itemForm.price" @input="setCurrency($event,itemForm,'price')" type="number" min="0" step="1" inputmode="numeric" required></label><label class="wide">Deskripsi<textarea v-model="itemForm.description" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="cancelItem()">Batal</button><button class="primary">{{editing.item?'Simpan Perubahan':'Simpan Barang'}}</button></div></form>
        <form v-else-if="modal==='customer'" class="grid" @submit.prevent="saveCustomer"><label>Kode Anggota<input v-model.trim="customerForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: AGT-001" required></label><label>Nama<input v-model.trim="customerForm.name" minlength="3" maxlength="120" required></label><label>Nomor Telepon<input v-model="customerForm.phone" type="tel" inputmode="numeric" minlength="8" maxlength="20" autocomplete="tel" placeholder="8–20 digit, contoh: 081234567890"></label><label class="wide">Alamat<textarea v-model="customerForm.address" maxlength="500"/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeCustomer">Batal</button><button class="primary">{{editing.customer?'Simpan Perubahan':'Simpan Pelanggan'}}</button></div></form>
        <form v-else class="grid" @submit.prevent="saveSupplier"><label>Kode Supplier<input v-model.trim="supplierForm.code" pattern="[A-Za-z0-9._\-]{2,50}" placeholder="Contoh: SUP-001" required></label><label>Nama<input v-model.trim="supplierForm.name" minlength="3" maxlength="100" required></label><label>Nomor Telepon<input v-model="supplierForm.phone" type="tel" inputmode="numeric" minlength="8" maxlength="20" autocomplete="tel" placeholder="8–20 digit, contoh: 081234567890" required></label><label class="wide">Alamat<textarea v-model="supplierForm.address" minlength="5" required/></label><div class="modal-actions wide"><button type="button" class="soft" @click="closeSupplier">Batal</button><button class="primary">{{editing.supplier?'Simpan Perubahan':'Simpan Supplier'}}</button></div></form>
      </section></div>
      <div v-if="userModal" class="modal-backdrop" @mousedown.self="closeUser"><section class="modal-card user-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>{{editingUser?'Ubah':'Tambah'}} Pengguna</h2><p>Password saat edit boleh dikosongkan jika tidak ingin diganti.</p></div><button class="modal-close" aria-label="Tutup" @click="closeUser">×</button></div><form class="grid" @submit.prevent="saveUser"><label>Nama<input v-model.trim="userForm.name" minlength="2" maxlength="100" required></label><label>Email<input v-model.trim="userForm.email" type="email" required></label><label>Password<input v-model="userForm.password" type="password" minlength="8" :required="!editingUser" autocomplete="new-password"></label><label>Role<select v-model="userForm.role" :disabled="String(editingUser)===String(currentUser.id)"><option value="admin">Admin</option><option value="cashier">Kasir</option><option value="viewer">Viewer</option></select><small v-if="String(editingUser)===String(currentUser.id)">Role akun sendiri tidak dapat diubah.</small></label><label class="check-label"><input v-model="userForm.active" type="checkbox" :disabled="String(editingUser)===String(currentUser.id)"> Akun aktif</label><div class="modal-actions wide"><button type="button" class="soft" @click="closeUser">Batal</button><button class="primary">Simpan</button></div></form></section></div>
    </main>
  </div>
</template>
